import React, { createContext, useContext, useState } from 'react';
import { SUPPORTED_LANGUAGES } from '../services/translationService';

const LanguageContext = createContext({});

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Onboarding
    welcome: "Welcome",
    tagline: "Recycle Smart, Earn Rewards",
    selectLanguage: "Select Your Language",
    continue: "Continue",
    getStarted: "Get Started",
    learnHow: "Learn How It Works",
    skip: "Skip Tutorial",
    congratulations: "Congratulations!",
    welcomeReward: "You've earned a reward!",
    tutorialStep1Title: "Scan QR Code",
    tutorialStep1Desc: "Find a smart dustbin and scan the QR code on it",
    tutorialStep2Title: "Enter Dustbin Code",
    tutorialStep2Desc: "Type the dustbin code from the QR in the app",
    tutorialStep3Title: "Dispose Your Waste",
    tutorialStep3Desc: "Properly dispose your recyclable waste in the dustbin",
    tutorialStep4Title: "Earn Rewards",
    tutorialStep4Desc: "Get instant rewards and discounts at partner outlets",
    tutorialStep5Title: "Make an Impact",
    tutorialStep5Desc: "Track your environmental contribution and see your impact",
    tutorialStep6Title: "Schedule Home Pickups",
    tutorialStep6Desc: "Book doorstep pickup for your recyclable waste through EcoRevive",
    next: "Next",
    finish: "Finish",
    signIn: "Sign In with Google",
    earnRewards: "Earn rewards for recycling",
    getDiscounts: "Get discounts at partner stores",
    helpPlanet: "Help create a cleaner planet",
    
    // Dashboard
    welcomeBack: "Welcome back",
    scanQRPrompt: "Scan a dustbin QR code and enter the code below to earn rewards",
    enterCode: "Enter Dustbin Code",
    enterCodePlaceholder: "Enter code (e.g., DBN001)",
    submit: "Submit & Earn Rewards",
    myRewards: "My Rewards",
    points: "Points",
    scanHistory: "Scan History",
    howItWorks: "How It Works",
    step1: "Find a Smart Dustbin",
    step1Desc: "Locate an EcoRewards smart dustbin near you",
    step2: "Scan QR Code",
    step2Desc: "Scan the QR code on the dustbin",
    step3: "Enter Code",
    step3Desc: "Enter the dustbin code in the app",
    step4: "Earn Rewards",
    step4Desc: "Get instant rewards and points",
    usageLimit: "Usage Limit",
    usageLimitDesc: "Strict Limit: Maximum 5 dustbin uses per day per user",
    citiesLeading: "Cities Making a Difference",
    citiesLeadingSub: "See which cities are leading the sustainability revolution",
    viewLeaderboard: "View Full Leaderboard",
    seeMoreCities: "See More Cities",
    participation: "Participation",
    wasteDiverted: "Waste Diverted",
    whatHappens: "What Happens to Your Trash?",
    collection: "Collection",
    collectionDesc: "Your waste is collected from our smart dustbins and sorted immediately at the source.",
    sorting: "Sorting",
    sortingDesc: "Advanced technology separates recyclables from non-recyclables with high precision.",
    recycling: "Recycling",
    recyclingDesc: "Recyclable materials are processed and transformed into new products.",
    energyRecovery: "Energy Recovery",
    energyRecoveryDesc: "Non-recyclable waste is converted to energy through eco-friendly waste-to-energy processes.",
    statsNote: "Note: Statistics shown are placeholder values for demonstration purposes",
    wasteFromLandfills: "Waste Diverted from Landfills",
    tonsRecycled: "Tons Recycled This Month",
    emissionsReduction: "Reduction in Harmful Emissions",
    
    // Leaderboard
    cityLeaderboard: "City Sustainability Leaderboard",
    cityLeaderboardSub: "Celebrating cities whose citizens are making the biggest environmental impact",
    wasteRecycledMonth: "Waste Recycled This Month",
    activeUsers: "Active Users",
    smartDustbins: "Smart Dustbins",
    back: "Back",
    whyMatters: "Why This Matters",
    citiesThrive: "Cities Thrive",
    citiesThriveDesc: "Cities with high EcoRewards participation see cleaner streets, reduced pollution, and improved quality of life for all residents.",
    realImpact: "Real Impact",
    realImpactDesc: "Every kilogram of waste recycled prevents harmful methane emissions and reduces landfill pollution, making our cities healthier.",
    winWin: "Win-Win Model",
    winWinDesc: "Citizens get rewards by using smart dustbins in public places while helping their city become cleaner and more sustainable for future generations.",
    
    // Report
    reportIssue: "Report an Issue",
    whatToReport: "What would you like to report?",
    selectIssue: "Select an issue type",
    brokenDustbin: "Broken Dustbin",
    fullDustbin: "Full Dustbin",
    technicalIssue: "Technical Issue",
    qrProblem: "QR Code Problem",
    locationIssue: "Location Issue",
    other: "Other",
    elaborate: "Please elaborate on the issue:",
    describeProblem: "Describe the problem in detail... (e.g., location, dustbin code, what happened)",
    cancel: "Cancel",
    submitReport: "Submit Report",
    
    // Messages
    thankYouReport: "Thank you for your report!\n\nWe have received your feedback and will address it soon.",
    selectIssueError: "Please select an issue type and provide details.",
    dailyLimitReached: "Daily limit reached! You can only use dustbins 5 times per day. Come back tomorrow!",
    enterDustbinCode: "Please enter a dustbin code",
    checkingLocation: "Checking your location...",
    locationVerified: "Location verified. Verifying code...",
    tooFar: "You're too far from the dustbin",
    getCloser: "Please get closer.",
    success: "Success!",
    earnedPoints: "You've earned",
    
    // EcoRevive
    kabadConnect: "EcoRevive",
    kabadConnectDesc: "Schedule pickups for recyclable waste from your home",
    schedulePickup: "Schedule Pickup",
    newPickup: "New Pickup",
    pastDeliveries: "Past Deliveries",
    pastDeliveriesDesc: "View your recycling history and environmental impact",
    ecoMissions: "Eco Missions",
    ecoMissionsDesc: "Complete challenges to earn extra rewards",
    
    // Waste Categories
    wastePaper: "Paper",
    wastePaperDesc: "Newspapers, magazines, cardboard boxes",
    wastePlastic: "Plastic",
    wastePlasticDesc: "Bottles, containers, packaging",
    wasteMetal: "Metal",
    wasteMetalDesc: "Cans, foils, metal scraps",
    wasteEwaste: "E-Waste",
    wasteEwasteDesc: "Electronics, batteries, gadgets",
    wasteMixed: "Mixed",
    wasteMixedDesc: "Combination of recyclable materials",
    
    // Pickup Form
    selectWasteType: "Select Waste Type",
    selectWasteTypeDesc: "Choose the category that best describes your waste",
    selectWasteCategory: "Please select a waste category",
    pickupDetails: "Pickup Details",
    pickupDetailsDesc: "Enter your address and preferred time slot",
    pickupAddress: "Pickup Address",
    enterFullAddress: "Enter your full address with landmark",
    pickupDate: "Pickup Date",
    phoneNumber: "Phone Number",
    preferredTime: "Preferred Time Slot",
    timeMorning: "Morning",
    timeAfternoon: "Afternoon",
    timeEvening: "Evening",
    additionalNotes: "Additional Notes",
    optional: "Optional",
    notesPlaceholder: "Any special instructions...",
    fillAllFields: "Please fill all required fields",
    
    // Pickup Confirmation
    confirmPickup: "Confirm Pickup",
    reviewDetails: "Review your pickup details",
    wasteType: "Waste Type",
    scheduledFor: "Scheduled For",
    recyclingPartner: "Verified Recycling Partner",
    rating: "Rating",
    yearsExp: "years experience",
    expectedArrival: "Expected Arrival",
    nextDay: "Within next day",
    priceNote: "💰 Price will be confirmed by your assigned partner based on waste type, quantity, and current market rates.",
    confirmBooking: "Confirm Booking",
    scheduling: "Scheduling...",
    pickupScheduled: "✅ Pickup Scheduled Successfully!\n\nYour recycling partner will contact you soon.",
    
    // Steps
    details: "Details",
    confirm: "Confirm",
    
    // Past Orders
    yourTotalImpact: "Your Total Environmental Impact",
    wasteRecycled: "Waste Recycled",
    co2Prevented: "CO₂ Prevented",
    co2Saved: "CO₂ saved",
    waterSaved: "Water saved",
    energySaved: "Energy saved",
    noOrders: "No Orders Yet",
    noOrdersDesc: "Start scheduling pickups to see your recycling history here",
    completed: "Completed",
    cancelled: "Cancelled",
    pending: "Pending",
    quantity: "Quantity",
    amount: "Amount",
    partner: "Partner",
    pointsEarned: "Points Earned",
    environmentalImpact: "Environmental Impact",
    viewDetails: "View Details",
    reorder: "Book Again",
    orderDetails: "Order Details",
    orderId: "Order ID",
    date: "Date",
    status: "Status",
    
    // Missions
    allMissions: "All Missions",
    weekly: "Weekly",
    monthly: "Monthly",
    special: "Special",
    missionsCompleted: "Missions Completed",
    rewardsEarned: "Points Earned",
    activeWeekly: "Active Weekly",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    legendary: "Legendary",
    claimReward: "Claim Reward",
    viewMission: "View Mission",
    missionTips: "Mission Tips",
    
    // Mission Examples
    missionPlastic2kg: "Recycle 2kg Plastic This Week",
    missionPlastic2kgDesc: "Help reduce plastic waste by recycling 2kg of plastic materials",
    missionDaily5Days: "5-Day Recycling Streak",
    missionDaily5DaysDesc: "Recycle waste for 5 consecutive days to maintain your streak",
    missionEwaste1kg: "E-Waste Warrior",
    missionEwaste1kgDesc: "Recycle 1kg of electronic waste this month",
    missionMixed3Types: "Variety Champion",
    missionMixed3TypesDesc: "Recycle 3 different types of waste this week",
    missionPaper10kg: "Paper Protector",
    missionPaper10kgDesc: "Save trees by recycling 10kg of paper this month",
    missionEcoWarrior: "Ultimate Eco Warrior",
    missionEcoWarriorDesc: "Complete all other missions to unlock this legendary achievement",
    
    missionTip1: "Complete daily pickups to maintain streaks and earn bonus points",
    missionTip2: "Separate your waste properly to maximize mission progress",
    missionTip3: "Weekly missions reset every Monday at midnight",
    missionTip4: "Share missions with friends to compete on the leaderboard",
    
    // Schedule Info
    howItWorksTitle: "How Pickup Works",
    pickupStep1: "Select your waste category (Paper, Plastic, Metal, E-waste, Mixed)",
    pickupStep2: "Enter pickup address, date, and preferred time slot",
    pickupStep3: "Get assigned a verified Recycling Partner nearby",
    pickupStep4: "Partner arrives, collects material, and weighs it",
    pickupStep5: "Get paid and earn EcoPoints instantly",
    
    whyChooseUs: "Why Choose EcoRevive?",
    benefit1: "Verified & Background-Checked Partners",
    benefit2: "Fair & Dynamic Pricing",
    benefit3: "Flexible Scheduling",
    benefit4: "Doorstep Pickup Service",
    benefit5: "Environmental Impact Tracking",
    scheduleNow: "Schedule Pickup Now"
  },
  hi: {
    // Onboarding
    welcome: "स्वागत है",
    tagline: "समझदारी से रीसायकल करें, इनाम पाएं",
    selectLanguage: "अपनी भाषा चुनें",
    continue: "आगे बढ़ें",
    getStarted: "शुरू करें",
    learnHow: "कैसे काम करता है जानें",
    skip: "छोड़ें",
    congratulations: "बधाई हो!",
    welcomeReward: "आपने इनाम पा लिया है!",
    tutorialStep1Title: "QR कोड स्कैन करें",
    tutorialStep1Desc: "स्मार्ट डस्टबिन ढूंढें और उस पर लगा QR कोड स्कैन करें",
    tutorialStep2Title: "डस्टबिन कोड डालें",
    tutorialStep2Desc: "QR से मिला डस्टबिन कोड ऐप में टाइप करें",
    tutorialStep3Title: "कचरा डालें",
    tutorialStep3Desc: "अपना रीसायकल करने योग्य कचरा डस्टबिन में सही तरीके से डालें",
    tutorialStep4Title: "इनाम पाएं",
    tutorialStep4Desc: "पार्टनर दुकानों पर तुरंत इनाम और छूट पाएं",
    tutorialStep5Title: "बदलाव लाएं",
    tutorialStep5Desc: "अपने पर्यावरण में योगदान को ट्रैक करें और अपना प्रभाव देखें",
    tutorialStep6Title: "घर पर पिकअप शेड्यूल करें",
    tutorialStep6Desc: "कबाड कनेक्ट के माध्यम से अपने रीसायकल योग्य कचरे के लिए घर पर पिकअप बुक करें",
    next: "आगे",
    finish: "पूरा करें",
    signIn: "Google से लॉगिन करें",
    earnRewards: "रीसायकल करके इनाम पाएं",
    getDiscounts: "पार्टनर स्टोर्स पर छूट पाएं",
    helpPlanet: "साफ-सुथरी धरती बनाने में मदद करें",
    
    // Dashboard
    welcomeBack: "वापसी पर स्वागत है",
    scanQRPrompt: "इनाम पाने के लिए डस्टबिन का QR कोड स्कैन करें और नीचे कोड डालें",
    enterCode: "डस्टबिन कोड डालें",
    enterCodePlaceholder: "कोड डालें (जैसे, DBN001)",
    submit: "जमा करें और इनाम पाएं",
    myRewards: "मेरे इनाम",
    points: "अंक",
    scanHistory: "स्कैन इतिहास",
    howItWorks: "कैसे काम करता है",
    step1: "स्मार्ट डस्टबिन खोजें",
    step1Desc: "अपने आस-पास EcoRewards स्मार्ट डस्टबिन ढूंढें",
    step2: "QR कोड स्कैन करें",
    step2Desc: "डस्टबिन पर लगा QR कोड स्कैन करें",
    step3: "कोड डालें",
    step3Desc: "ऐप में डस्टबिन कोड डालें",
    step4: "इनाम पाएं",
    step4Desc: "तुरंत इनाम और अंक पाएं",
    usageLimit: "उपयोग सीमा",
    usageLimitDesc: "सख्त सीमा: प्रति उपयोगकर्ता प्रतिदिन अधिकतम 5 बार डस्टबिन का उपयोग",
    citiesLeading: "शहर बदलाव ला रहे हैं",
    citiesLeadingSub: "देखें कौन से शहर स्थिरता में अग्रणी हैं",
    viewLeaderboard: "पूरी लीडरबोर्ड देखें",
    seeMoreCities: "और शहर देखें",
    participation: "भागीदारी",
    wasteDiverted: "कचरा हटाया गया",
    whatHappens: "आपके कचरे का क्या होता है?",
    collection: "संग्रह",
    collectionDesc: "आपका कचरा हमारे स्मार्ट डस्टबिन से एकत्र कर तुरंत छांटा जाता है।",
    sorting: "छंटाई",
    sortingDesc: "उन्नत तकनीक रीसायकल योग्य को गैर-रीसायकल योग्य से अलग करती है।",
    recycling: "रीसाइक्लिंग",
    recyclingDesc: "रीसायकल योग्य सामग्री को नए उत्पादों में बदला जाता है।",
    energyRecovery: "ऊर्जा पुनर्प्राप्ति",
    energyRecoveryDesc: "गैर-रीसायकल योग्य कचरे को पर्यावरण अनुकूल तरीके से ऊर्जा में बदला जाता है।",
    statsNote: "नोट: दिखाए गए आंकड़े प्रदर्शन के लिए उदाहरण मूल्य हैं",
    wasteFromLandfills: "लैंडफिल से हटाया गया कचरा",
    tonsRecycled: "इस महीने रीसायकल किए गए टन",
    emissionsReduction: "हानिकारक उत्सर्जन में कमी",
    
    // Leaderboard
    cityLeaderboard: "शहरी स्थिरता लीडरबोर्ड",
    cityLeaderboardSub: "उन शहरों का जश्न जिनके नागरिक सबसे बड़ा पर्यावरणीय प्रभाव डाल रहे हैं",
    wasteRecycledMonth: "इस महीने रीसायकल किया गया कचरा",
    activeUsers: "सक्रिय उपयोगकर्ता",
    smartDustbins: "स्मार्ट डस्टबिन",
    back: "वापस",
    whyMatters: "यह क्यों मायने रखता है",
    citiesThrive: "शहर फलते-फूलते हैं",
    citiesThriveDesc: "उच्च EcoRewards भागीदारी वाले शहरों में स्वच्छ सड़कें, कम प्रदूषण और बेहतर जीवन गुणवत्ता देखी जाती है।",
    realImpact: "वास्तविक प्रभाव",
    realImpactDesc: "रीसायकल किया गया हर किलो कचरा हानिकारक मीथेन उत्सर्जन को रोकता है और लैंडफिल प्रदूषण कम करता है।",
    winWin: "दोनों के लिए फायदेमंद",
    winWinDesc: "नागरिक स्मार्ट डस्टबिन का उपयोग कर इनाम पाते हैं और अपने शहर को स्वच्छ बनाने में मदद करते हैं।",
    
    // Report
    reportIssue: "समस्या रिपोर्ट करें",
    whatToReport: "आप क्या रिपोर्ट करना चाहते हैं?",
    selectIssue: "समस्या का प्रकार चुनें",
    brokenDustbin: "टूटा हुआ डस्टबिन",
    fullDustbin: "भरा हुआ डस्टबिन",
    technicalIssue: "तकनीकी समस्या",
    qrProblem: "QR कोड समस्या",
    locationIssue: "स्थान समस्या",
    other: "अन्य",
    elaborate: "कृपया समस्या विस्तार से बताएं:",
    describeProblem: "समस्या विस्तार से बताएं... (जैसे, स्थान, डस्टबिन कोड, क्या हुआ)",
    cancel: "रद्द करें",
    submitReport: "रिपोर्ट जमा करें",
    
    // Messages
    thankYouReport: "आपकी रिपोर्ट के लिए धन्यवाद!\n\nहमें आपकी प्रतिक्रिया मिल गई है और जल्द ही इसे हल किया जाएगा।",
    selectIssueError: "कृपया समस्या का प्रकार चुनें और विवरण दें।",
    dailyLimitReached: "दैनिक सीमा पूरी हो गई! आप प्रतिदिन केवल 5 बार डस्टबिन का उपयोग कर सकते हैं। कल वापस आएं!",
    enterDustbinCode: "कृपया डस्टबिन कोड डालें",
    checkingLocation: "आपका स्थान जांचा जा रहा है...",
    locationVerified: "स्थान सत्यापित। कोड जांचा जा रहा है...",
    tooFar: "आप डस्टबिन से बहुत दूर हैं",
    getCloser: "कृपया पास आएं।",
    success: "सफलता!",
    earnedPoints: "आपने कमाए",
    
    // EcoRevive
    kabadConnect: "EcoRevive",
    kabadConnectDesc: "घर से रीसायकल योग्य कचरे के लिए पिकअप शेड्यूल करें",
    smartDustbins: "स्मार्ट डस्टबिन",
    schedulePickup: "पिकअप शेड्यूल करें",
    newPickup: "नया पिकअप",
    pastDeliveries: "पिछली डिलीवरी",
    pastDeliveriesDesc: "अपना रीसायकलिंग इतिहास और पर्यावरण प्रभाव देखें",
    ecoMissions: "इको मिशन",
    ecoMissionsDesc: "अतिरिक्त पुरस्कार पाने के लिए चुनौतियां पूरी करें",
    
    // Waste Categories
    wastePaper: "कागज",
    wastePaperDesc: "अखबार, पत्रिकाएं, गत्ते के बक्से",
    wastePlastic: "प्लास्टिक",
    wastePlasticDesc: "बोतलें, कंटेनर, पैकेजिंग",
    wasteMetal: "धातु",
    wasteMetalDesc: "डिब्बे, फॉयल, धातु के टुकड़े",
    wasteEwaste: "ई-कचरा",
    wasteEwasteDesc: "इलेक्ट्रॉनिक्स, बैटरियां, गैजेट",
    wasteMixed: "मिश्रित",
    wasteMixedDesc: "रीसायकल योग्य सामग्री का संयोजन",
    
    // Pickup Form
    selectWasteType: "कचरे का प्रकार चुनें",
    selectWasteTypeDesc: "वह श्रेणी चुनें जो आपके कचरे का सबसे अच्छा वर्णन करती है",
    selectWasteCategory: "कृपया एक कचरा श्रेणी चुनें",
    pickupDetails: "पिकअप विवरण",
    pickupDetailsDesc: "अपना पता और पसंदीदा समय स्लॉट दर्ज करें",
    pickupAddress: "पिकअप पता",
    enterFullAddress: "लैंडमार्क के साथ अपना पूरा पता दर्ज करें",
    pickupDate: "पिकअप तिथि",
    phoneNumber: "फोन नंबर",
    preferredTime: "पसंदीदा समय स्लॉट",
    timeMorning: "सुबह",
    timeAfternoon: "दोपहर",
    timeEvening: "शाम",
    additionalNotes: "अतिरिक्त नोट्स",
    optional: "वैकल्पिक",
    notesPlaceholder: "कोई विशेष निर्देश...",
    fillAllFields: "कृपया सभी आवश्यक फ़ील्ड भरें",
    
    // Pickup Confirmation
    confirmPickup: "पिकअप की पुष्टि करें",
    reviewDetails: "अपने पिकअप विवरण की समीक्षा करें",
    wasteType: "कचरे का प्रकार",
    scheduledFor: "शेड्यूल किया गया",
    recyclingPartner: "सत्यापित रीसायकलिंग पार्टनर",
    rating: "रेटिंग",
    yearsExp: "वर्षों का अनुभव",
    expectedArrival: "अपेक्षित आगमन",
    nextDay: "अगले दिन के भीतर",
    priceNote: "💰 कीमत आपके नियुक्त पार्टनर द्वारा कचरे के प्रकार, मात्रा और वर्तमान बाजार दरों के आधार पर पुष्टि की जाएगी।",
    confirmBooking: "बुकिंग की पुष्टि करें",
    scheduling: "शेड्यूल हो रहा है...",
    pickupScheduled: "✅ पिकअप सफलतापूर्वक शेड्यूल!\n\nआपका रीसायकलिंग पार्टनर जल्द ही संपर्क करेगा।",
    
    // Steps
    details: "विवरण",
    confirm: "पुष्टि करें",
    
    // Past Orders
    yourTotalImpact: "आपका कुल पर्यावरण प्रभाव",
    wasteRecycled: "रीसायकल किया गया कचरा",
    co2Prevented: "CO₂ रोका गया",
    co2Saved: "CO₂ बचाया",
    waterSaved: "पानी बचाया",
    energySaved: "ऊर्जा बचाई",
    noOrders: "अभी तक कोई ऑर्डर नहीं",
    noOrdersDesc: "अपना रीसायकलिंग इतिहास यहां देखने के लिए पिकअप शेड्यूल करना शुरू करें",
    completed: "पूर्ण",
    cancelled: "रद्द",
    pending: "लंबित",
    quantity: "मात्रा",
    amount: "राशि",
    partner: "पार्टनर",
    pointsEarned: "अंक अर्जित",
    environmentalImpact: "पर्यावरणीय प्रभाव",
    viewDetails: "विवरण देखें",
    reorder: "फिर से बुक करें",
    orderDetails: "ऑर्डर विवरण",
    orderId: "ऑर्डर आईडी",
    date: "तिथि",
    status: "स्थिति",
    
    // Missions
    allMissions: "सभी मिशन",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    special: "विशेष",
    missionsCompleted: "मिशन पूर्ण",
    rewardsEarned: "अंक अर्जित",
    activeWeekly: "सक्रिय साप्ताहिक",
    easy: "आसान",
    medium: "मध्यम",
    hard: "कठिन",
    legendary: "महान",
    claimReward: "पुरस्कार प्राप्त करें",
    viewMission: "मिशन देखें",
    missionTips: "मिशन टिप्स",
    
    // Mission Examples
    missionPlastic2kg: "इस सप्ताह 2kg प्लास्टिक रीसायकल करें",
    missionPlastic2kgDesc: "2kg प्लास्टिक सामग्री रीसायकल करके प्लास्टिक कचरा कम करने में मदद करें",
    missionDaily5Days: "5-दिन की रीसायकलिंग स्ट्रीक",
    missionDaily5DaysDesc: "अपनी स्ट्रीक बनाए रखने के लिए लगातार 5 दिनों तक कचरा रीसायकल करें",
    missionEwaste1kg: "ई-कचरा योद्धा",
    missionEwaste1kgDesc: "इस महीने 1kg इलेक्ट्रॉनिक कचरा रीसायकल करें",
    missionMixed3Types: "विविधता चैंपियन",
    missionMixed3TypesDesc: "इस सप्ताह 3 विभिन्न प्रकार के कचरे को रीसायकल करें",
    missionPaper10kg: "कागज रक्षक",
    missionPaper10kgDesc: "इस महीने 10kg कागज रीसायकल करके पेड़ बचाएं",
    missionEcoWarrior: "परम इको योद्धा",
    missionEcoWarriorDesc: "इस महान उपलब्धि को अनलॉक करने के लिए अन्य सभी मिशन पूरे करें",
    
    missionTip1: "स्ट्रीक बनाए रखने और बोनस अंक अर्जित करने के लिए दैनिक पिकअप पूरा करें",
    missionTip2: "मिशन प्रगति को अधिकतम करने के लिए अपने कचरे को ठीक से अलग करें",
    missionTip3: "साप्ताहिक मिशन हर सोमवार आधी रात को रीसेट होते हैं",
    missionTip4: "लीडरबोर्ड पर प्रतिस्पर्धा करने के लिए दोस्तों के साथ मिशन साझा करें",
    
    // Schedule Info
    howItWorksTitle: "पिकअप कैसे काम करता है",
    pickupStep1: "अपनी कचरा श्रेणी चुनें (कागज, प्लास्टिक, धातु, ई-कचरा, मिश्रित)",
    pickupStep2: "पिकअप पता, तिथि और पसंदीदा समय स्लॉट दर्ज करें",
    pickupStep3: "पास में एक सत्यापित रीसायकलिंग पार्टनर नियुक्त करें",
    pickupStep4: "पार्टनर आता है, सामग्री एकत्र करता है, और तौलता है",
    pickupStep5: "भुगतान पाएं और तुरंत इकोपॉइंट्स अर्जित करें",
    
    whyChooseUs: "कबाड कनेक्ट क्यों चुनें?",
    benefit1: "सत्यापित और बैकग्राउंड-चेक किए गए पार्टनर",
    benefit2: "निष्पक्ष और गतिशील मूल्य निर्धारण",
    benefit3: "लचीला शेड्यूलिंग",
    benefit4: "घर पर पिकअप सेवा",
    benefit5: "पर्यावरणीय प्रभाव ट्रैकिंग",
    scheduleNow: "अभी पिकअप शेड्यूल करें"
  },
  te: {
    // Onboarding
    welcome: "స్వాగతం",
    tagline: "తెలివిగా రీసైకిల్ చేసి, బహుమతులు పొందండి",
    selectLanguage: "మీ భాషను ఎంచుకోండి",
    continue: "కొనసాగించండి",
    getStarted: "ప్రారంభించండి",
    learnHow: "ఎలా పనిచేస్తుందో తెలుసుకోండి",
    skip: "దాటవేయండి",
    congratulations: "అభినందనలు!",
    welcomeReward: "మీరు బహుమతిని సంపాదించారు!",
    tutorialStep1Title: "QR కోడ్ స్కాన్ చేయండి",
    tutorialStep1Desc: "స్మార్ట్ డస్ట్‌బిన్‌ను కనుగొని, దానిపై ఉన్న QR కోడ్‌ను స్కాన్ చేయండి",
    tutorialStep2Title: "డస్ట్‌బిన్ కోడ్ ఎంటర్ చేయండి",
    tutorialStep2Desc: "QR నుండి వచ్చిన డస్ట్‌బిన్ కోడ్‌ను యాప్‌లో టైప్ చేయండి",
    tutorialStep3Title: "చెత్తను వేయండి",
    tutorialStep3Desc: "రీసైకిల్ చేయగల మీ చెత్తను డస్ట్‌బిన్‌లో సరిగ్గా వేయండి",
    tutorialStep4Title: "బహుమతులు పొందండి",
    tutorialStep4Desc: "పార్టనర్ దుకాణాల్లో తక్షణ బహుమతులు మరియు డిస్కౌంట్లు పొందండి",
    tutorialStep5Title: "మార్పు తెచ్చండి",
    tutorialStep5Desc: "మీ పర్యావరణ సహకారాన్ని ట్రాక్ చేసి, మీ ప్రభావాన్ని చూడండి",
    tutorialStep6Title: "ఇంటి పికప్‌లను షెడ్యూల్ చేయండి",
    tutorialStep6Desc: "కబాడ్ కనెక్ట్ ద్వారా మీ రీసైకిల్ చేయదగిన వ్యర్థాల కోసం డోర్‌స్టెప్ పికప్ బుక్ చేయండి",
    next: "తరువాత",
    finish: "పూర్తి",
    signIn: "Google తో లాగిన్ అవ్వండి",
    earnRewards: "రీసైక్లింగ్ చేసి బహుమతులు పొందండి",
    getDiscounts: "పార్టనర్ స్టోర్లలో డిస్కౌంట్లు పొందండి",
    helpPlanet: "శుభ్రమైన గ్రహాన్ని తయారు చేయడంలో సహాయపడండి",
    
    // Dashboard
    welcomeBack: "తిరిగి స్వాగతం",
    scanQRPrompt: "బహుమతులు పొందడానికి డస్ట్‌బిన్ QR కోడ్ స్కాన్ చేసి కింద కోడ్ ఎంటర్ చేయండి",
    enterCode: "డస్ట్‌బిన్ కోడ్ ఎంటర్ చేయండి",
    enterCodePlaceholder: "కోడ్ ఎంటర్ చేయండి (ఉదా., DBN001)",
    submit: "సబ్మిట్ చేసి బహుమతులు పొందండి",
    myRewards: "నా బహుమతులు",
    points: "పాయింట్లు",
    scanHistory: "స్కాన్ చరిత్ర",
    howItWorks: "ఎలా పనిచేస్తుంది",
    step1: "స్మార్ట్ డస్ట్‌బిన్ కనుగొనండి",
    step1Desc: "మీ దగ్గర EcoRewards స్మార్ట్ డస్ట్‌బిన్‌ను కనుగొనండి",
    step2: "QR కోడ్ స్కాన్ చేయండి",
    step2Desc: "డస్ట్‌బిన్‌పై ఉన్న QR కోడ్‌ను స్కాన్ చేయండి",
    step3: "కోడ్ ఎంటర్ చేయండి",
    step3Desc: "యాప్‌లో డస్ట్‌బిన్ కోడ్ ఎంటర్ చేయండి",
    step4: "బహుమతులు సంపాదించండి",
    step4Desc: "తక్షణ బహుమతులు మరియు పాయింట్లు పొందండి",
    usageLimit: "వాడుక పరిమితి",
    usageLimitDesc: "కఠిన పరిమితి: ప్రతి వినియోగదారుకు రోజుకు గరిష్టంగా 5 సార్లు డస్ట్‌బిన్ వాడుక",
    citiesLeading: "నగరాలు మార్పు తెస్తున్నాయి",
    citiesLeadingSub: "ఏ నగరాలు స్థిరత్వంలో ముందున్నాయో చూడండి",
    viewLeaderboard: "పూర్తి లీడర్‌బోర్డ్ చూడండి",
    seeMoreCities: "మరిన్ని నగరాలు చూడండి",
    participation: "పాల్గొనడం",
    wasteDiverted: "చెత్త మళ్లించబడింది",
    whatHappens: "మీ చెత్తకు ఏమవుతుంది?",
    collection: "సేకరణ",
    collectionDesc: "మీ చెత్త మా స్మార్ట్ డస్ట్‌బిన్‌ల నుండి సేకరించి వెంటనే క్రమబద్ధీకరించబడుతుంది।",
    sorting: "క్రమబద్ధీకరణ",
    sortingDesc: "అధునాతన సాంకేతికత రీసైకిల్ చేయగలవాటిని మరియు చేయలేని వాటిని వేరు చేస్తుంది।",
    recycling: "రీసైక్లింగ్",
    recyclingDesc: "రీసైకిల్ చేయగల పదార్థాలను కొత్త ఉత్పత్తులుగా మారుస్తారు।",
    energyRecovery: "శక్తి పునరుద్ధరణ",
    energyRecoveryDesc: "రీసైకిల్ చేయలేని చెత్తను పర్యావరణ అనుకూల పద్ధతిలో శక్తిగా మారుస్తారు।",
    statsNote: "గమనిక: చూపించిన గణాంకాలు ప్రదర్శన కోసం ఉదాహరణ విలువలు",
    wasteFromLandfills: "ల్యాండ్‌ఫిల్‌ల నుండి మళ్లించిన చెత్త",
    tonsRecycled: "ఈ నెలలో రీసైకిల్ చేసిన టన్నులు",
    emissionsReduction: "హానికర ఉద్గారాల తగ్గింపు",
    
    // Leaderboard
    cityLeaderboard: "నగర స్థిరత్వ లీడర్‌బోర్డ్",
    cityLeaderboardSub: "అత్యధిక పర్యావరణ ప్రభావాన్ని చూపుతున్న నగరాల పౌరులను జరుపుకుందాం",
    wasteRecycledMonth: "ఈ నెలలో రీసైకిల్ చేసిన చెత్త",
    activeUsers: "క్రియాశీల వినియోగదారులు",
    smartDustbins: "స్మార్ట్ డస్ట్‌బిన్‌లు",
    back: "వెనుకకు",
    whyMatters: "ఇది ఎందుకు ముఖ్యం",
    citiesThrive: "నగరాలు అభివృద్ధి చెందుతాయి",
    citiesThriveDesc: "అధిక EcoRewards పాల్గొనడం ఉన్న నగరాలలో స్వచ్ఛమైన వీధులు, తక్కువ కాలుష్యం మరియు మెరుగైన జీవన నాణ్యత కనిపిస్తుంది।",
    realImpact: "నిజమైన ప్రభావం",
    realImpactDesc: "రీసైకిల్ చేసిన ప్రతి కిలో చెత్త హానికర మీథేన్ ఉద్గారాలను నిరోధిస్తుంది మరియు ల్యాండ్‌ఫిల్ కాలుష్యాన్ని తగ్గిస్తుంది।",
    winWin: "రెండింటికీ లాభం",
    winWinDesc: "పౌరులు స్మార్ట్ డస్ట్‌బిన్‌లను ఉపయోగించి బహుమతులు పొందుతారు మరియు తమ నగరాన్ని స్వచ్ఛంగా మారుస్తారు।",
    
    // Report
    reportIssue: "సమస్యను నివేదించండి",
    whatToReport: "మీరు ఏమి నివేదించాలనుకుంటున్నారు?",
    selectIssue: "సమస్య రకాన్ని ఎంచుకోండి",
    brokenDustbin: "విరిగిన డస్ట్‌బిన్",
    fullDustbin: "నిండిన డస్ట్‌బిన్",
    technicalIssue: "సాంకేతిక సమస్య",
    qrProblem: "QR కోడ్ సమస్య",
    locationIssue: "స్థానం సమస్య",
    other: "ఇతరం",
    elaborate: "దయచేసి సమస్యను వివరంగా చెప్పండి:",
    describeProblem: "సమస్యను వివరంగా వివరించండి... (ఉదా., స్థానం, డస్ట్‌బిన్ కోడ్, ఏమి జరిగింది)",
    cancel: "రద్దు చేయి",
    submitReport: "నివేదిక సమర్పించండి",
    
    // Messages
    thankYouReport: "మీ నివేదిక కోసం ధన్యవాదాలు!\n\nమేము మీ అభిప్రాయాన్ని అందుకున్నాము మరియు త్వరలో దానిని పరిష్కరిస్తాము।",
    selectIssueError: "దయచేసి సమస్య రకాన్ని ఎంచుకోండి మరియు వివరాలు ఇవ్వండి।",
    dailyLimitReached: "రోజువారీ పరిమితి చేరుకుంది! మీరు రోజుకు కేవలం 5 సార్లు మాత్రమే డస్ట్‌బిన్‌లను ఉపయోగించవచ్చు। రేపు తిరిగి రండి!",
    enterDustbinCode: "దయచేసి డస్ట్‌బిన్ కోడ్ ఎంటర్ చేయండి",
    checkingLocation: "మీ స్థానాన్ని తనిఖీ చేస్తోంది...",
    locationVerified: "స్థానం ధృవీకరించబడింది। కోడ్ తనిఖీ చేస్తోంది...",
    tooFar: "మీరు డస్ట్‌బిన్ నుండి చాలా దూరంగా ఉన్నారు",
    getCloser: "దయచేసి దగ్గరకు రండి।",
    success: "విజయం!",
    earnedPoints: "మీరు సంపాదించారు",
    
    // EcoRevive (Telugu - using simplified translations)
    kabadConnect: "EcoRevive",
    kabadConnectDesc: "ఇంటి నుండి రీసైకిల్ చేయదగిన వ్యర్థాల కోసం పికప్ షెడ్యూల్ చేయండి",
    smartDustbins: "స్మార్ట్ డస్ట్‌బిన్‌లు",
    schedulePickup: "పికప్ షెడ్యూల్ చేయండి",
    newPickup: "కొత్త పికప్",
    pastDeliveries: "గత డెలివరీలు",
    pastDeliveriesDesc: "మీ రీసైక్లింగ్ చరిత్ర మరియు పర్యావరణ ప్రభావాన్ని చూడండి",
    ecoMissions: "ఎకో మిషన్లు",
    ecoMissionsDesc: "అదనపు బహుమతులను పొందడానికి సవాళ్లను పూర్తి చేయండి",
    wastePaper: "కాగితం",
    wastePaperDesc: "వార్తాపత్రికలు, పత్రికలు, కార్డ్‌బోర్డ్ బాక్సులు",
    wastePlastic: "ప్లాస్టిక్",
    wastePlasticDesc: "సీసాలు, కంటైనర్లు, ప్యాకేజింగ్",
    wasteMetal: "మెటల్",
    wasteMetalDesc: "డబ్బాలు, ఫాయిల్స్, మెటల్ స్క్రాప్స్",
    wasteEwaste: "ఇ-వ్యర్థం",
    wasteEwasteDesc: "ఎలక్ట్రానిక్స్, బ్యాటరీలు, గాడ్జెట్స్",
    wasteMixed: "మిశ్రమ",
    wasteMixedDesc: "రీసైకిల్ చేయదగిన పదార్థాల కలయిక",
    selectWasteType: "వ్యర్థ రకాన్ని ఎంచుకోండి",
    selectWasteTypeDesc: "మీ వ్యర్థాన్ని ఉత్తమంగా వివరించే వర్గాన్ని ఎంచుకోండి",
    selectWasteCategory: "దయచేసి వ్యర్థ వర్గాన్ని ఎంచుకోండి",
    pickupDetails: "పికప్ వివరాలు",
    pickupDetailsDesc: "మీ చిరునామా మరియు ఇష్టమైన సమయ స్లాట్‌ను నమోదు చేయండి",
    pickupAddress: "పికప్ చిరునామా",
    enterFullAddress: "ల్యాండ్‌మార్క్‌తో మీ పూర్తి చిరునామాను నమోదు చేయండి",
    pickupDate: "పికప్ తేదీ",
    phoneNumber: "ఫోన్ నంబర్",
    preferredTime: "ఇష్టమైన సమయ స్లాట్",
    timeMorning: "ఉదయం",
    timeAfternoon: "మధ్యాహ్నం",
    timeEvening: "సాయంత్రం",
    additionalNotes: "అదనపు గమనికలు",
    optional: "ఐచ్ఛికం",
    notesPlaceholder: "ఏదైనా ప్రత్యేక సూచనలు...",
    fillAllFields: "దయచేసి అన్ని అవసర ఫీల్డ్‌లను పూరించండి",
    confirmPickup: "పికప్ నిర్ధారించండి",
    reviewDetails: "మీ పికప్ వివరాలను సమీక్షించండి",
    wasteType: "వ్యర్థ రకం",
    scheduledFor: "షెడ్యూల్ చేయబడింది",
    recyclingPartner: "ధృవీకరించబడిన రీసైక్లింగ్ భాగస్వామి",
    rating: "రేటింగ్",
    yearsExp: "సంవత్సరాల అనుభవం",
    expectedArrival: "అంచనా రాక",
    nextDay: "తదుపరి రోజులో",
    priceNote: "💰 ధర మీ నియమిత భాగస్వామి ద్వారా వ్యర్థ రకం, పరిమాణం మరియు ప్రస్తుత మార్కెట్ ధరల ఆధారంగా నిర్ధారించబడుతుంది।",
    confirmBooking: "బుకింగ్ నిర్ధారించండి",
    scheduling: "షెడ్యూల్ చేస్తోంది...",
    pickupScheduled: "✅ పికప్ విజయవంతంగా షెడ్యూల్ చేయబడింది!\n\nమీ రీసైక్లింగ్ భాగస్వామి త్వరలో సంప్రదిస్తారు।",
    details: "వివరాలు",
    confirm: "నిర్ధారించండి",
    yourTotalImpact: "మీ మొత్తం పర్యావరణ ప్రభావం",
    wasteRecycled: "రీసైకిల్ చేయబడిన వ్యర్థం",
    co2Prevented: "CO₂ నివారించబడింది",
    co2Saved: "CO₂ సేవ్ చేయబడింది",
    waterSaved: "నీరు సేవ్ చేయబడింది",
    energySaved: "శక్తి సేవ్ చేయబడింది",
    noOrders: "ఇంకా ఆర్డర్లు లేవు",
    noOrdersDesc: "మీ రీసైక్లింగ్ చరిత్రను ఇక్కడ చూడటానికి పికప్‌లను షెడ్యూల్ చేయడం ప్రారంభించండి",
    completed: "పూర్తయింది",
    cancelled: "రద్దు చేయబడింది",
    pending: "పెండింగ్",
    quantity: "పరిమాణం",
    amount: "మొత్తం",
    partner: "భాగస్వామి",
    pointsEarned: "పాయింట్లు సంపాదించారు",
    environmentalImpact: "పర్యావరణ ప్రభావం",
    viewDetails: "వివరాలను చూడండి",
    reorder: "మళ్లీ బుక్ చేయండి",
    orderDetails: "ఆర్డర్ వివరాలు",
    orderId: "ఆర్డర్ ID",
    date: "తేదీ",
    status: "స్థితి",
    allMissions: "అన్ని మిషన్లు",
    weekly: "వారం",
    monthly: "నెల",
    special: "ప్రత్యేక",
    missionsCompleted: "మిషన్లు పూర్తయ్యాయి",
    rewardsEarned: "పాయింట్లు సంపాదించారు",
    activeWeekly: "యాక్టివ్ వీక్లీ",
    easy: "సులభం",
    medium: "మధ్యస్థం",
    hard: "కష్టం",
    legendary: "పురాణ",
    claimReward: "బహుమతిని క్లెయిమ్ చేయండి",
    viewMission: "మిషన్ చూడండి",
    missionTips: "మిషన్ చిట్కాలు",
    missionPlastic2kg: "ఈ వారం 2kg ప్లాస్టిక్ రీసైకిల్ చేయండి",
    missionPlastic2kgDesc: "2kg ప్లాస్టిక్ పదార్థాలను రీసైకిల్ చేయడం ద్వారా ప్లాస్టిక్ వ్యర్థాలను తగ్గించడంలో సహాయపడండి",
    missionDaily5Days: "5-రోజుల రీసైక్లింగ్ స్ట్రీక్",
    missionDaily5DaysDesc: "మీ స్ట్రీక్‌ను నిర్వహించడానికి వరుసగా 5 రోజులు వ్యర్థాలను రీసైకిల్ చేయండి",
    missionEwaste1kg: "ఇ-వ్యర్థ యోధుడు",
    missionEwaste1kgDesc: "ఈ నెలలో 1kg ఎలక్ట్రానిక్ వ్యర్థాలను రీసైకిల్ చేయండి",
    missionMixed3Types: "వైవిధ్య ఛాంపియన్",
    missionMixed3TypesDesc: "ఈ వారం 3 విభిన్న రకాల వ్యర్థాలను రీసైకిల్ చేయండి",
    missionPaper10kg: "కాగితం రక్షకుడు",
    missionPaper10kgDesc: "ఈ నెలలో 10kg కాగితాన్ని రీసైకిల్ చేయడం ద్వారా చెట్లను కాపాడండి",
    missionEcoWarrior: "అంతిమ ఎకో యోధుడు",
    missionEcoWarriorDesc: "ఈ పురాణ సాధనను అన్‌లాక్ చేయడానికి అన్ని ఇతర మిషన్లను పూర్తి చేయండి",
    missionTip1: "స్ట్రీక్‌లను నిర్వహించడానికి మరియు బోనస్ పాయింట్లను సంపాదించడానికి రోజువారీ పికప్‌లను పూర్తి చేయండి",
    missionTip2: "మిషన్ పురోగతిని పెంచడానికి మీ వ్యర్థాలను సరిగ్గా వేరు చేయండి",
    missionTip3: "వారంవారీ మిషన్లు ప్రతి సోమవారం అర్ధరాత్రి రీసెట్ అవుతాయి",
    missionTip4: "లీడర్‌బోర్డ్‌లో పోటీపడటానికి స్నేహితులతో మిషన్లను భాగస్వామ్యం చేయండి",
    howItWorksTitle: "పికప్ ఎలా పనిచేస్తుంది",
    pickupStep1: "మీ వ్యర్థ వర్గాన్ని ఎంచుకోండి (కాగితం, ప్లాస్టిక్, మెటల్, ఇ-వ్యర్థం, మిశ్రమ)",
    pickupStep2: "పికప్ చిరునామా, తేదీ మరియు ఇష్టమైన సమయ స్లాట్‌ను నమోదు చేయండి",
    pickupStep3: "సమీపంలో ధృవీకరించబడిన రీసైక్లింగ్ భాగస్వామిని కేటాయించండి",
    pickupStep4: "భాగస్వామి వచ్చి, పదార్థాలను సేకరిస్తారు మరియు బరువు వేస్తారు",
    pickupStep5: "చెల్లింపు పొందండి మరియు తక్షణమే ఎకో పాయింట్లను సంపాదించండి",
    whyChooseUs: "కబాడ్ కనెక్ట్‌ను ఎందుకు ఎంచుకోవాలి?",
    benefit1: "ధృవీకరించబడిన మరియు నేపథ్య తనిఖీ చేయబడిన భాగస్వాములు",
    benefit2: "న్యాయమైన మరియు డైనమిక్ ధర",
    benefit3: "సౌకర్యవంతమైన షెడ్యూలింగ్",
    benefit4: "ఇంటి వద్ద పికప్ సేవ",
    benefit5: "పర్యావరణ ప్రభావ ట్రాకింగ్",
    scheduleNow: "ఇప్పుడు పికప్ షెడ్యూల్ చేయండి"
  },
  ta: {
    // Onboarding
    welcome: "வரவேற்கிறோம்",
    tagline: "புத்திசாலித்தனமாக மறுசுழற்சி செய்யுங்கள், வெகுமதிகளைப் பெறுங்கள்",
    selectLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    continue: "தொடரவும்",
    getStarted: "தொடங்குங்கள்",
    learnHow: "எப்படி செயல்படுகிறது என்பதை அறியவும்",
    skip: "தவிர்க்கவும்",
    congratulations: "வாழ்த்துக்கள்!",
    welcomeReward: "நீங்கள் வெகுமதியைப் பெற்றுள்ளீர்கள்!",
    tutorialStep1Title: "QR குறியீட்டை ஸ்கேன் செய்யவும்",
    tutorialStep1Desc: "ஸ்மார்ட் டஸ்ட்பினைக் கண்டுபிடித்து அதில் உள்ள QR குறியீட்டை ஸ்கேன் செய்யவும்",
    tutorialStep2Title: "டஸ்ட்பின் குறியீட்டை உள்ளிடவும்",
    tutorialStep2Desc: "QR இலிருந்து கிடைத்த டஸ்ட்பின் குறியீட்டை ஆப்பில் டைப் செய்யவும்",
    tutorialStep3Title: "கழிவுகளை அகற்றவும்",
    tutorialStep3Desc: "உங்கள் மறுசுழற்சி செய்யக்கூடிய கழிவுகளை டஸ்ட்பினில் சரியாக அகற்றவும்",
    tutorialStep4Title: "வெகுமதிகளைப் பெறுங்கள்",
    tutorialStep4Desc: "கூட்டாண்மை கடைகளில் உடனடி வெகுமதிகள் மற்றும் தள்ளுபடிகளைப் பெறுங்கள்",
    tutorialStep5Title: "மாற்றத்தை உருவாக்குங்கள்",
    tutorialStep5Desc: "உங்கள் சுற்றுச்சூழல் பங்களிப்பைக் கண்காணித்து உங்கள் தாக்கத்தைப் பார்க்கவும்",
    tutorialStep6Title: "வீட்டு பிக்அப்களை திட்டமிடுங்கள்",
    tutorialStep6Desc: "கபாட் கனெக்ட் மூலம் உங்கள் மறுசுழற்சி செய்யக்கூடிய கழிவுகளுக்கு வீட்டு வாசல் பிக்அப்பை புக் செய்யவும்",
    next: "அடுத்து",
    finish: "முடிவு",
    signIn: "Google மூலம் உள்நுழையவும்",
    earnRewards: "மறுசுழற்சிக்கு வெகுமதிகளைப் பெறுங்கள்",
    getDiscounts: "கூட்டாண்மை கடைகளில் தள்ளுபடிகளைப் பெறுங்கள்",
    helpPlanet: "தூய்மையான கிரகத்தை உருவாக்க உதவுங்கள்",
    
    // Dashboard
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    scanQRPrompt: "வெகுமதிகளைப் பெற டஸ்ட்பின் QR குறியீட்டை ஸ்கேன் செய்து கீழே குறியீட்டை உள்ளிடவும்",
    enterCode: "டஸ்ட்பின் குறியீட்டை உள்ளிடவும்",
    enterCodePlaceholder: "குறியீட்டை உள்ளிடவும் (எ.கா., DBN001)",
    submit: "சமர்ப்பித்து வெகுமதிகளைப் பெறுங்கள்",
    myRewards: "எனது வெகுமதிகள்",
    points: "புள்ளிகள்",
    scanHistory: "ஸ்கேன் வரலாறு",
    howItWorks: "எப்படி செயல்படுகிறது",
    step1: "ஸ்மார்ட் டஸ்ட்பினைக் கண்டறியவும்",
    step1Desc: "உங்களுக்கு அருகில் உள்ள EcoRewards ஸ்மார்ட் டஸ்ட்பினைக் கண்டுபிடிக்கவும்",
    step2: "QR குறியீட்டை ஸ்கேன் செய்யவும்",
    step2Desc: "டஸ்ட்பினில் உள்ள QR குறியீட்டை ஸ்கேன் செய்யவும்",
    step3: "குறியீட்டை உள்ளிடவும்",
    step3Desc: "ஆப்ஸில் டஸ்ட்பின் குறியீட்டை உள்ளிடவும்",
    step4: "வெகுமதிகளைப் பெறுங்கள்",
    step4Desc: "உடனடி வெகுமதிகள் மற்றும் புள்ளிகளைப் பெறுங்கள்",
    usageLimit: "பயன்பாட்டு வரம்பு",
    usageLimitDesc: "கடுமையான வரம்பு: ஒரு பயனருக்கு ஒரு நாளைக்கு அதிகபட்சம் 5 முறை டஸ்ட்பின் பயன்பாடு",
    citiesLeading: "மாற்றத்தை உருவாக்கும் நகரங்கள்",
    citiesLeadingSub: "நிலைத்தன்மையில் முன்னணியில் இருக்கும் நகரங்களைப் பாருங்கள்",
    viewLeaderboard: "முழு லீடர்போர்டைப் பார்க்கவும்",
    seeMoreCities: "மேலும் நகரங்களைப் பார்க்கவும்",
    participation: "பங்கேற்பு",
    wasteDiverted: "திசை திருப்பப்பட்ட கழிவு",
    whatHappens: "உங்கள் குப்பைக்கு என்ன நடக்கிறது?",
    collection: "சேகரிப்பு",
    collectionDesc: "உங்கள் கழிவு எங்கள் ஸ்மார்ட் டஸ்ட்பின்களில் இருந்து சேகரிக்கப்பட்டு உடனடியாக வரிசைப்படுத்தப்படுகிறது.",
    sorting: "வரிசைப்படுத்துதல்",
    sortingDesc: "மேம்பட்ட தொழில்நுட்பம் மறுசுழற்சி செய்யக்கூடியவை மற்றும் செய்ய முடியாதவற்றைப் பிரிக்கிறது.",
    recycling: "மறுசுழற்சி",
    recyclingDesc: "மறுசுழற்சி செய்யக்கூடிய பொருட்கள் புதிய தயாரிப்புகளாக மாற்றப்படுகின்றன.",
    energyRecovery: "ஆற்றல் மீட்பு",
    energyRecoveryDesc: "மறுசுழற்சி செய்ய முடியாத கழிவு சுற்றுச்சூழல் நட்பு முறையில் ஆற்றலாக மாற்றப்படுகிறது.",
    statsNote: "குறிப்பு: காட்டப்பட்ட புள்ளிவிவரங்கள் ஆர்ப்பாட்ட நோக்கங்களுக்கான உதாரண மதிப்புகள்",
    wasteFromLandfills: "நிலப்பரப்பில் இருந்து திசை திருப்பப்பட்ட கழிவு",
    tonsRecycled: "இந்த மாதம் மறுசுழற்சி செய்யப்பட்ட டன்கள்",
    emissionsReduction: "தீங்கு விளைவிக்கும் உமிழ்வுகளில் குறைப்பு",
    
    // Leaderboard
    cityLeaderboard: "நகர நிலைத்தன்மை லீடர்போர்டு",
    cityLeaderboardSub: "மிகப்பெரிய சுற்றுச்சூழல் தாக்கத்தை ஏற்படுத்தும் நகரங்களின் குடிமக்களைக் கொண்டாடுங்கள்",
    wasteRecycledMonth: "இந்த மாதம் மறுசுழற்சி செய்யப்பட்ட கழிவு",
    activeUsers: "செயலில் உள்ள பயனர்கள்",
    smartDustbins: "ஸ்மார்ட் டஸ்ட்பின்கள்",
    back: "பின்னால்",
    whyMatters: "இது ஏன் முக்கியம்",
    citiesThrive: "நகரங்கள் செழிக்கின்றன",
    citiesThriveDesc: "அதிக EcoRewards பங்கேற்பு உள்ள நகரங்களில் சுத்தமான தெருக்கள், குறைந்த மாசுபாடு மற்றும் மேம்பட்ட வாழ்க்கைத் தரம் காணப்படுகிறது.",
    realImpact: "உண்மையான தாக்கம்",
    realImpactDesc: "மறுசுழற்சி செய்யப்படும் ஒவ்வொரு கிலோ கழிவும் தீங்கு விளைவிக்கும் மீத்தேன் உமிழ்வைத் தடுக்கிறது மற்றும் நிலப்பரப்பு மாசுபாட்டைக் குறைக்கிறது.",
    winWin: "இரு தரப்பினருக்கும் லாபம்",
    winWinDesc: "குடிமக்கள் ஸ்மார்ட் டஸ்ட்பின்களைப் பயன்படுத்தி வெகுமதிகளைப் பெறுகிறார்கள் மற்றும் தங்கள் நகரத்தை சுத்தமாக மாற்ற உதவுகிறார்கள்.",
    
    // Report
    reportIssue: "சிக்கலைப் புகாரளிக்கவும்",
    whatToReport: "நீங்கள் என்ன புகாரளிக்க விரும்புகிறீர்கள்?",
    selectIssue: "சிக்கல் வகையைத் தேர்ந்தெடுக்கவும்",
    brokenDustbin: "உடைந்த டஸ்ட்பின்",
    fullDustbin: "நிறைந்த டஸ்ட்பின்",
    technicalIssue: "தொழில்நுட்ப சிக்கல்",
    qrProblem: "QR குறியீட்டு சிக்கல்",
    locationIssue: "இட சிக்கல்",
    other: "மற்றவை",
    elaborate: "தயவுசெய்து சிக்கலை விரிவாக விளக்கவும்:",
    describeProblem: "சிக்கலை விரிவாக விவரிக்கவும்... (எ.கா., இடம், டஸ்ட்பின் குறியீடு, என்ன நடந்தது)",
    cancel: "ரத்து செய்",
    submitReport: "புகார் சமர்ப்பிக்கவும்",
    
    // Messages
    thankYouReport: "உங்கள் புகாருக்கு நன்றி!\n\nஎங்களுக்கு உங்கள் கருத்து கிடைத்துள்ளது, விரைவில் அதைத் தீர்ப்போம்.",
    selectIssueError: "தயவுசெய்து சிக்கல் வகையைத் தேர்ந்தெடுத்து விவரங்களை வழங்கவும்.",
    dailyLimitReached: "தினசரி வரம்பு அடைந்தது! நீங்கள் ஒரு நாளைக்கு 5 முறை மட்டுமே டஸ்ட்பின்களைப் பயன்படுத்த முடியும். நாளை மீண்டும் வாருங்கள்!",
    enterDustbinCode: "தயவுசெய்து டஸ்ட்பின் குறியீட்டை உள்ளிடவும்",
    checkingLocation: "உங்கள் இடத்தைச் சரிபார்க்கிறது...",
    locationVerified: "இடம் சரிபார்க்கப்பட்டது। குறியீடு சரிபார்க்கப்படுகிறது...",
    tooFar: "நீங்கள் டஸ்ட்பினிலிருந்து மிகவும் தொலைவில் இருக்கிறீர்கள்",
    getCloser: "தயவுசெய்து நெருக்கமாக வாருங்கள்.",
    success: "வெற்றி!",
    earnedPoints: "நீங்கள் சம்பாதித்துள்ளீர்கள்",
    
    // EcoRevive (Tamil - using same structure as Telugu for consistency)
    kabadConnect: "EcoRevive",
    kabadConnectDesc: "வீட்டிலிருந்து மறுசுழற்சி செய்யக்கூடிய கழிவுகளுக்கு பிக்அப்பை திட்டமிடுங்கள்",
    smartDustbins: "ஸ்மார்ட் டஸ்ட்பின்கள்",
    schedulePickup: "பிக்அப் திட்டமிடுங்கள்",
    newPickup: "புதிய பிக்அப்",
    pastDeliveries: "கடந்த டெலிவரிகள்",
    pastDeliveriesDesc: "உங்கள் மறுசுழற்சி வரலாறு மற்றும் சுற்றுச்சூழல் தாக்கத்தைப் பார்க்கவும்",
    ecoMissions: "ஈகோ மிஷன்கள்",
    ecoMissionsDesc: "கூடுதல் வெகுமதிகளை பெற சவால்களை முடிக்கவும்",
    wastePaper: "காகிதம்",
    wastePaperDesc: "செய்தித்தாள்கள், பத்திரிகைகள், அட்டைப் பெட்டிகள்",
    wastePlastic: "பிளாஸ்டிக்",
    wastePlasticDesc: "பாட்டில்கள், கொள்கலன்கள், பேக்கேஜிங்",
    wasteMetal: "உலோகம்",
    wasteMetalDesc: "டின்கள், ஃபாயில்கள், உலோக ஸ்கிராப்கள்",
    wasteEwaste: "மின்னணு கழிவு",
    wasteEwasteDesc: "மின்னணுவியல், பேட்டரிகள், கேட்ஜெட்கள்",
    wasteMixed: "கலவை",
    wasteMixedDesc: "மறுசுழற்சி செய்யக்கூடிய பொருட்களின் கலவை",
    selectWasteType: "கழிவு வகையைத் தேர்ந்தெடுக்கவும்",
    selectWasteTypeDesc: "உங்கள் கழிவை சிறப்பாக விவரிக்கும் வகையைத் தேர்ந்தெடுக்கவும்",
    selectWasteCategory: "தயவுசெய்து கழிவு வகையைத் தேர்ந்தெடுக்கவும்",
    pickupDetails: "பிக்அப் விவரங்கள்",
    pickupDetailsDesc: "உங்கள் முகவரி மற்றும் விருப்பமான நேர இடைவெளியை உள்ளிடவும்",
    pickupAddress: "பிக்அப் முகவரி",
    enterFullAddress: "அடையாளத்துடன் உங்கள் முழு முகவரியை உள்ளிடவும்",
    pickupDate: "பிக்அப் தேதி",
    phoneNumber: "தொலைபேசி எண்",
    preferredTime: "விருப்பமான நேர இடைவெளி",
    timeMorning: "காலை",
    timeAfternoon: "மதியம்",
    timeEvening: "மாலை",
    additionalNotes: "கூடுதல் குறிப்புகள்",
    optional: "விருப்பத்தேர்வு",
    notesPlaceholder: "ஏதேனும் சிறப்பு அறிவுறுத்தல்கள்...",
    fillAllFields: "தயவுசெய்து அனைத்து தேவையான புலங்களையும் நிரப்பவும்",
    confirmPickup: "பிக்அப்பை உறுதிப்படுத்தவும்",
    reviewDetails: "உங்கள் பிக்அப் விவரங்களை மதிப்பாய்வு செய்யவும்",
    wasteType: "கழிவு வகை",
    scheduledFor: "திட்டமிடப்பட்டது",
    recyclingPartner: "சரிபார்க்கப்பட்ட மறுசுழற்சி கூட்டாளர்",
    rating: "மதிப்பீடு",
    yearsExp: "ஆண்டுகள் அனுபவம்",
    expectedArrival: "எதிர்பார்க்கப்படும் வருகை",
    nextDay: "அடுத்த நாளுக்குள்",
    priceNote: "💰 விலை உங்கள் நியமிக்கப்பட்ட கூட்டாளரால் கழிவு வகை, அளவு மற்றும் தற்போதைய சந்தை விலைகளின் அடிப்படையில் உறுதிப்படுத்தப்படும்.",
    confirmBooking: "முன்பதிவை உறுதிப்படுத்தவும்",
    scheduling: "திட்டமிடப்படுகிறது...",
    pickupScheduled: "✅ பிக்அப் வெற்றிகரமாக திட்டமிடப்பட்டது!\n\nஉங்கள் மறுசுழற்சி கூட்டாளர் விரைவில் தொடர்பு கொள்வார்.",
    details: "விவரங்கள்",
    confirm: "உறுதிப்படுத்தவும்",
    yourTotalImpact: "உங்கள் மொத்த சுற்றுச்சூழல் தாக்கம்",
    wasteRecycled: "மறுசுழற்சி செய்யப்பட்ட கழிவு",
    co2Prevented: "CO₂ தடுக்கப்பட்டது",
    co2Saved: "CO₂ சேமிக்கப்பட்டது",
    waterSaved: "நீர் சேமிக்கப்பட்டது",
    energySaved: "ஆற்றல் சேமிக்கப்பட்டது",
    noOrders: "இன்னும் ஆர்டர்கள் இல்லை",
    noOrdersDesc: "உங்கள் மறுசுழற்சி வரலாற்றை இங்கு பார்க்க பிக்அப்களை திட்டமிடத் தொடங்குங்கள்",
    completed: "முடிந்தது",
    cancelled: "ரத்துசெய்யப்பட்டது",
    pending: "நிலுவையில்",
    quantity: "அளவு",
    amount: "தொகை",
    partner: "கூட்டாளர்",
    pointsEarned: "புள்ளிகள் சம்பாதித்தீர்கள்",
    environmentalImpact: "சுற்றுச்சூழல் தாக்கம்",
    viewDetails: "விவரங்களைப் பார்க்கவும்",
    reorder: "மீண்டும் புக் செய்யவும்",
    orderDetails: "ஆர்டர் விவரங்கள்",
    orderId: "ஆர்டர் ஐடி",
    date: "தேதி",
    status: "நிலை",
    allMissions: "அனைத்து மிஷன்கள்",
    weekly: "வாரம்",
    monthly: "மாதம்",
    special: "சிறப்பு",
    missionsCompleted: "மிஷன்கள் முடிந்தது",
    rewardsEarned: "புள்ளிகள் சம்பாதித்தீர்கள்",
    activeWeekly: "செயலில் உள்ள வாரம்",
    easy: "எளிதானது",
    medium: "நடுத்தரம்",
    hard: "கடினமானது",
    legendary: "புராண",
    claimReward: "வெகுமதியை க்ளெய்ம் செய்யவும்",
    viewMission: "மிஷனைப் பார்க்கவும்",
    missionTips: "மிஷன் குறிப்புகள்",
    missionPlastic2kg: "இந்த வாரம் 2kg பிளாஸ்டிக் மறுசுழற்சி செய்யவும்",
    missionPlastic2kgDesc: "2kg பிளாஸ்டிக் பொருட்களை மறுசுழற்சி செய்வதன் மூலம் பிளாஸ்டிக் கழிவைக் குறைக்க உதவவும்",
    missionDaily5Days: "5-நாள் மறுசுழற்சி ஸ்ட்ரீக்",
    missionDaily5DaysDesc: "உங்கள் ஸ்ட்ரீக்கைப் பராமரிக்க தொடர்ச்சியாக 5 நாட்கள் கழிவுகளை மறுசுழற்சி செய்யவும்",
    missionEwaste1kg: "மின்னணு கழிவு வீரர்",
    missionEwaste1kgDesc: "இந்த மாதம் 1kg மின்னணு கழிவுகளை மறுசுழற்சி செய்யவும்",
    missionMixed3Types: "வகைப்பாடு சாம்பியன்",
    missionMixed3TypesDesc: "இந்த வாரம் 3 வெவ்வேறு வகை கழிவுகளை மறுசுழற்சி செய்யவும்",
    missionPaper10kg: "காகித பாதுகாவலர்",
    missionPaper10kgDesc: "இந்த மாதம் 10kg காகிதத்தை மறுசுழற்சி செய்வதன் மூலம் மரங்களைக் காப்பாற்றவும்",
    missionEcoWarrior: "இறுதி ஈகோ வீரர்",
    missionEcoWarriorDesc: "இந்த புராண சாதனையைத் திறக்க மற்ற அனைத்து மிஷன்களையும் முடிக்கவும்",
    missionTip1: "ஸ்ட்ரீக்குகளைப் பராமரிக்கவும் போனஸ் புள்ளிகளை சம்பாதிக்கவும் தினசரி பிக்அப்களை முடிக்கவும்",
    missionTip2: "மிஷன் முன்னேற்றத்தை அதிகரிக்க உங்கள் கழிவுகளைச் சரியாக பிரிக்கவும்",
    missionTip3: "வாராந்திர மிஷன்கள் ஒவ்வொரு திங்கட்கிழமை நள்ளிரவில் மீட்டமைக்கப்படும்",
    missionTip4: "லீடர்போர்டில் போட்டியிட நண்பர்களுடன் மிஷன்களைப் பகிரவும்",
    howItWorksTitle: "பிக்அப் எப்படி வேலை செய்கிறது",
    pickupStep1: "உங்கள் கழிவு வகையைத் தேர்ந்தெடுக்கவும் (காகிதம், பிளாஸ்டிக், உலோகம், மின்னணு கழிவு, கலவை)",
    pickupStep2: "பிக்அப் முகவரி, தேதி மற்றும் விருப்பமான நேர இடைவெளியை உள்ளிடவும்",
    pickupStep3: "அருகில் உள்ள சரிபார்க்கப்பட்ட மறுசுழற்சி கூட்டாளரை நியமிக்கவும்",
    pickupStep4: "கூட்டாளர் வந்து, பொருட்களை சேகரித்து, எடை போடுவார்",
    pickupStep5: "பணம் பெறவும் மற்றும் உடனடியாக ஈகோ புள்ளிகளை சம்பாதிக்கவும்",
    whyChooseUs: "கபாட் கனெக்ட்டை ஏன் தேர்வு செய்ய வேண்டும்?",
    benefit1: "சரிபார்க்கப்பட்ட மற்றும் பின்னணி சோதனை செய்யப்பட்ட கூட்டாளர்கள்",
    benefit2: "நியாயமான மற்றும் டைனமிக் விலை",
    benefit3: "நெகிழ்வான திட்டமிடல்",
    benefit4: "வீட்டு வாசலில் பிக்அப் சேவை",
    benefit5: "சுற்றுச்சூழல் தாக்க கண்காணிப்பு",
    scheduleNow: "இப்போது பிக்அப் திட்டமிடுங்கள்"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  // Translation function - only uses hardcoded translations
  const t = (key) => {
    // Use hardcoded translations only
    return translations[language || 'en']?.[key] || translations['en']?.[key] || key;
  };

  const value = {
    language,
    changeLanguage,
    t,
    translations,
    supportedLanguages: SUPPORTED_LANGUAGES
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

