import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext({});

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Onboarding
    welcome: "Welcome to EcoRewards",
    tagline: "Recycle Smart, Earn Rewards",
    selectLanguage: "Select Your Language",
    continue: "Continue",
    getStarted: "Get Started",
    learnHow: "Learn How It Works",
    skip: "Skip Tutorial",
    congratulations: "Congratulations!",
    welcomeReward: "You've earned a reward!",
    tutorialStep1Title: "Scan QR Code",
    tutorialStep1Desc: "Find a smart dustbin and scan the QR code on it",
    tutorialStep2Title: "Enter Dustbin Code",
    tutorialStep2Desc: "Type the dustbin code from the QR in the app",
    tutorialStep3Title: "Dispose Your Waste",
    tutorialStep3Desc: "Properly dispose your recyclable waste in the dustbin",
    tutorialStep4Title: "Earn Rewards",
    tutorialStep4Desc: "Get instant rewards and discounts at partner outlets",
    tutorialStep5Title: "Make an Impact",
    tutorialStep5Desc: "Track your environmental contribution and see your impact",
    next: "Next",
    finish: "Finish",
    signIn: "Sign In with Google",
    earnRewards: "Earn rewards for recycling",
    getDiscounts: "Get discounts at partner stores",
    helpPlanet: "Help create a cleaner planet",
    
    // Dashboard
    welcomeBack: "Welcome back",
    scanQRPrompt: "Scan a dustbin QR code and enter the code below to earn rewards",
    enterCode: "Enter Dustbin Code",
    enterCodePlaceholder: "Enter code (e.g., DBN001)",
    submit: "Submit & Earn Rewards",
    myRewards: "My Rewards",
    points: "Points",
    scanHistory: "Scan History",
    howItWorks: "How It Works",
    step1: "Find a Smart Dustbin",
    step1Desc: "Locate an EcoRewards smart dustbin near you",
    step2: "Scan QR Code",
    step2Desc: "Scan the QR code on the dustbin",
    step3: "Enter Code",
    step3Desc: "Enter the dustbin code in the app",
    step4: "Earn Rewards",
    step4Desc: "Get instant rewards and points",
    usageLimit: "Usage Limit",
    usageLimitDesc: "Strict Limit: Maximum 2 dustbin uses per day per user",
    citiesLeading: "Cities Making a Difference",
    citiesLeadingSub: "See which cities are leading the sustainability revolution",
    viewLeaderboard: "View Full Leaderboard",
    seeMoreCities: "See More Cities",
    participation: "Participation",
    wasteDiverted: "Waste Diverted",
    whatHappens: "What Happens to Your Trash?",
    collection: "Collection",
    collectionDesc: "Your waste is collected from our smart dustbins and sorted immediately at the source.",
    sorting: "Sorting",
    sortingDesc: "Advanced technology separates recyclables from non-recyclables with high precision.",
    recycling: "Recycling",
    recyclingDesc: "Recyclable materials are processed and transformed into new products.",
    energyRecovery: "Energy Recovery",
    energyRecoveryDesc: "Non-recyclable waste is converted to energy through eco-friendly waste-to-energy processes.",
    statsNote: "Note: Statistics shown are placeholder values for demonstration purposes",
    wasteFromLandfills: "Waste Diverted from Landfills",
    tonsRecycled: "Tons Recycled This Month",
    emissionsReduction: "Reduction in Harmful Emissions",
    
    // Leaderboard
    cityLeaderboard: "City Sustainability Leaderboard",
    cityLeaderboardSub: "Celebrating cities whose citizens are making the biggest environmental impact",
    wasteRecycledMonth: "Waste Recycled This Month",
    activeUsers: "Active Users",
    smartDustbins: "Smart Dustbins",
    back: "Back",
    whyMatters: "Why This Matters",
    citiesThrive: "Cities Thrive",
    citiesThriveDesc: "Cities with high EcoRewards participation see cleaner streets, reduced pollution, and improved quality of life for all residents.",
    realImpact: "Real Impact",
    realImpactDesc: "Every kilogram of waste recycled prevents harmful methane emissions and reduces landfill pollution, making our cities healthier.",
    winWin: "Win-Win Model",
    winWinDesc: "Citizens get rewards by using smart dustbins in public places while helping their city become cleaner and more sustainable for future generations.",
    
    // Report
    reportIssue: "Report an Issue",
    whatToReport: "What would you like to report?",
    selectIssue: "Select an issue type",
    brokenDustbin: "Broken Dustbin",
    fullDustbin: "Full Dustbin",
    technicalIssue: "Technical Issue",
    qrProblem: "QR Code Problem",
    locationIssue: "Location Issue",
    other: "Other",
    elaborate: "Please elaborate on the issue:",
    describeProblem: "Describe the problem in detail... (e.g., location, dustbin code, what happened)",
    cancel: "Cancel",
    submitReport: "Submit Report",
    
    // Messages
    thankYouReport: "Thank you for your report!\n\nWe have received your feedback and will address it soon.",
    selectIssueError: "Please select an issue type and provide details.",
    dailyLimitReached: "Daily limit reached! You can only use dustbins 5 times per day. Come back tomorrow!",
    enterDustbinCode: "Please enter a dustbin code",
    checkingLocation: "Checking your location...",
    locationVerified: "Location verified. Verifying code...",
    tooFar: "You're too far from the dustbin",
    getCloser: "Please get closer.",
    success: "Success!",
    earnedPoints: "You've earned"
  },
  hi: {
    // Onboarding
    welcome: "EcoRewards में आपका स्वागत है",
    tagline: "समझदारी से रीसायकल करें, इनाम पाएं",
    selectLanguage: "अपनी भाषा चुनें",
    continue: "आगे बढ़ें",
    getStarted: "शुरू करें",
    learnHow: "कैसे काम करता है जानें",
    skip: "छोड़ें",
    congratulations: "बधाई हो!",
    welcomeReward: "आपने इनाम पा लिया है!",
    tutorialStep1Title: "QR कोड स्कैन करें",
    tutorialStep1Desc: "स्मार्ट डस्टबिन ढूंढें और उस पर लगा QR कोड स्कैन करें",
    tutorialStep2Title: "डस्टबिन कोड डालें",
    tutorialStep2Desc: "QR से मिला डस्टबिन कोड ऐप में टाइप करें",
    tutorialStep3Title: "कचरा डालें",
    tutorialStep3Desc: "अपना रीसायकल करने योग्य कचरा डस्टबिन में सही तरीके से डालें",
    tutorialStep4Title: "इनाम पाएं",
    tutorialStep4Desc: "पार्टनर दुकानों पर तुरंत इनाम और छूट पाएं",
    tutorialStep5Title: "बदलाव लाएं",
    tutorialStep5Desc: "अपने पर्यावरण में योगदान को ट्रैक करें और अपना प्रभाव देखें",
    next: "आगे",
    finish: "पूरा करें",
    signIn: "Google से लॉगिन करें",
    earnRewards: "रीसायकल करके इनाम पाएं",
    getDiscounts: "पार्टनर स्टोर्स पर छूट पाएं",
    helpPlanet: "साफ-सुथरी धरती बनाने में मदद करें",
    
    // Dashboard
    welcomeBack: "वापसी पर स्वागत है",
    scanQRPrompt: "इनाम पाने के लिए डस्टबिन का QR कोड स्कैन करें और नीचे कोड डालें",
    enterCode: "डस्टबिन कोड डालें",
    enterCodePlaceholder: "कोड डालें (जैसे, DBN001)",
    submit: "जमा करें और इनाम पाएं",
    myRewards: "मेरे इनाम",
    points: "अंक",
    scanHistory: "स्कैन इतिहास",
    howItWorks: "कैसे काम करता है",
    step1: "स्मार्ट डस्टबिन खोजें",
    step1Desc: "अपने आस-पास EcoRewards स्मार्ट डस्टबिन ढूंढें",
    step2: "QR कोड स्कैन करें",
    step2Desc: "डस्टबिन पर लगा QR कोड स्कैन करें",
    step3: "कोड डालें",
    step3Desc: "ऐप में डस्टबिन कोड डालें",
    step4: "इनाम पाएं",
    step4Desc: "तुरंत इनाम और अंक पाएं",
    usageLimit: "उपयोग सीमा",
    usageLimitDesc: "सख्त सीमा: प्रति उपयोगकर्ता प्रतिदिन अधिकतम 2 बार डस्टबिन का उपयोग",
    citiesLeading: "शहर बदलाव ला रहे हैं",
    citiesLeadingSub: "देखें कौन से शहर स्थिरता में अग्रणी हैं",
    viewLeaderboard: "पूरी लीडरबोर्ड देखें",
    seeMoreCities: "और शहर देखें",
    participation: "भागीदारी",
    wasteDiverted: "कचरा हटाया गया",
    whatHappens: "आपके कचरे का क्या होता है?",
    collection: "संग्रह",
    collectionDesc: "आपका कचरा हमारे स्मार्ट डस्टबिन से एकत्र कर तुरंत छांटा जाता है।",
    sorting: "छंटाई",
    sortingDesc: "उन्नत तकनीक रीसायकल योग्य को गैर-रीसायकल योग्य से अलग करती है।",
    recycling: "रीसाइक्लिंग",
    recyclingDesc: "रीसायकल योग्य सामग्री को नए उत्पादों में बदला जाता है।",
    energyRecovery: "ऊर्जा पुनर्प्राप्ति",
    energyRecoveryDesc: "गैर-रीसायकल योग्य कचरे को पर्यावरण अनुकूल तरीके से ऊर्जा में बदला जाता है।",
    statsNote: "नोट: दिखाए गए आंकड़े प्रदर्शन के लिए उदाहरण मूल्य हैं",
    wasteFromLandfills: "लैंडफिल से हटाया गया कचरा",
    tonsRecycled: "इस महीने रीसायकल किए गए टन",
    emissionsReduction: "हानिकारक उत्सर्जन में कमी",
    
    // Leaderboard
    cityLeaderboard: "शहरी स्थिरता लीडरबोर्ड",
    cityLeaderboardSub: "उन शहरों का जश्न जिनके नागरिक सबसे बड़ा पर्यावरणीय प्रभाव डाल रहे हैं",
    wasteRecycledMonth: "इस महीने रीसायकल किया गया कचरा",
    activeUsers: "सक्रिय उपयोगकर्ता",
    smartDustbins: "स्मार्ट डस्टबिन",
    back: "वापस",
    whyMatters: "यह क्यों मायने रखता है",
    citiesThrive: "शहर फलते-फूलते हैं",
    citiesThriveDesc: "उच्च EcoRewards भागीदारी वाले शहरों में स्वच्छ सड़कें, कम प्रदूषण और बेहतर जीवन गुणवत्ता देखी जाती है।",
    realImpact: "वास्तविक प्रभाव",
    realImpactDesc: "रीसायकल किया गया हर किलो कचरा हानिकारक मीथेन उत्सर्जन को रोकता है और लैंडफिल प्रदूषण कम करता है।",
    winWin: "दोनों के लिए फायदेमंद",
    winWinDesc: "नागरिक स्मार्ट डस्टबिन का उपयोग कर इनाम पाते हैं और अपने शहर को स्वच्छ बनाने में मदद करते हैं।",
    
    // Report
    reportIssue: "समस्या रिपोर्ट करें",
    whatToReport: "आप क्या रिपोर्ट करना चाहते हैं?",
    selectIssue: "समस्या का प्रकार चुनें",
    brokenDustbin: "टूटा हुआ डस्टबिन",
    fullDustbin: "भरा हुआ डस्टबिन",
    technicalIssue: "तकनीकी समस्या",
    qrProblem: "QR कोड समस्या",
    locationIssue: "स्थान समस्या",
    other: "अन्य",
    elaborate: "कृपया समस्या विस्तार से बताएं:",
    describeProblem: "समस्या विस्तार से बताएं... (जैसे, स्थान, डस्टबिन कोड, क्या हुआ)",
    cancel: "रद्द करें",
    submitReport: "रिपोर्ट जमा करें",
    
    // Messages
    thankYouReport: "आपकी रिपोर्ट के लिए धन्यवाद!\n\nहमें आपकी प्रतिक्रिया मिल गई है और जल्द ही इसे हल किया जाएगा।",
    selectIssueError: "कृपया समस्या का प्रकार चुनें और विवरण दें।",
    dailyLimitReached: "दैनिक सीमा पूरी हो गई! आप प्रतिदिन केवल 5 बार डस्टबिन का उपयोग कर सकते हैं। कल वापस आएं!",
    enterDustbinCode: "कृपया डस्टबिन कोड डालें",
    checkingLocation: "आपका स्थान जांचा जा रहा है...",
    locationVerified: "स्थान सत्यापित। कोड जांचा जा रहा है...",
    tooFar: "आप डस्टबिन से बहुत दूर हैं",
    getCloser: "कृपया पास आएं।",
    success: "सफलता!",
    earnedPoints: "आपने कमाए"
  },
  te: {
    // Onboarding
    welcome: "EcoRewards కి స్వాగతం",
    tagline: "తెలివిగా రీసైకిల్ చేసి, బహుమతులు పొందండి",
    selectLanguage: "మీ భాషను ఎంచుకోండి",
    continue: "కొనసాగించండి",
    getStarted: "ప్రారంభించండి",
    learnHow: "ఎలా పనిచేస్తుందో తెలుసుకోండి",
    skip: "దాటవేయండి",
    congratulations: "అభినందనలు!",
    welcomeReward: "మీరు బహుమతిని సంపాదించారు!",
    tutorialStep1Title: "QR కోడ్ స్కాన్ చేయండి",
    tutorialStep1Desc: "స్మార్ట్ డస్ట్‌బిన్‌ను కనుగొని, దానిపై ఉన్న QR కోడ్‌ను స్కాన్ చేయండి",
    tutorialStep2Title: "డస్ట్‌బిన్ కోడ్ ఎంటర్ చేయండి",
    tutorialStep2Desc: "QR నుండి వచ్చిన డస్ట్‌బిన్ కోడ్‌ను యాప్‌లో టైప్ చేయండి",
    tutorialStep3Title: "చెత్తను వేయండి",
    tutorialStep3Desc: "రీసైకిల్ చేయగల మీ చెత్తను డస్ట్‌బిన్‌లో సరిగ్గా వేయండి",
    tutorialStep4Title: "బహుమతులు పొందండి",
    tutorialStep4Desc: "పార్టనర్ దుకాణాల్లో తక్షణ బహుమతులు మరియు డిస్కౌంట్లు పొందండి",
    tutorialStep5Title: "మార్పు తెచ్చండి",
    tutorialStep5Desc: "మీ పర్యావరణ సహకారాన్ని ట్రాక్ చేసి, మీ ప్రభావాన్ని చూడండి",
    next: "తరువాత",
    finish: "పూర్తి",
    signIn: "Google తో లాగిన్ అవ్వండి",
    earnRewards: "రీసైక్లింగ్ చేసి బహుమతులు పొందండి",
    getDiscounts: "పార్టనర్ స్టోర్లలో డిస్కౌంట్లు పొందండి",
    helpPlanet: "శుభ్రమైన గ్రహాన్ని తయారు చేయడంలో సహాయపడండి",
    
    // Dashboard
    welcomeBack: "తిరిగి స్వాగతం",
    scanQRPrompt: "బహుమతులు పొందడానికి డస్ట్‌బిన్ QR కోడ్ స్కాన్ చేసి కింద కోడ్ ఎంటర్ చేయండి",
    enterCode: "డస్ట్‌బిన్ కోడ్ ఎంటర్ చేయండి",
    enterCodePlaceholder: "కోడ్ ఎంటర్ చేయండి (ఉదా., DBN001)",
    submit: "సబ్మిట్ చేసి బహుమతులు పొందండి",
    myRewards: "నా బహుమతులు",
    points: "పాయింట్లు",
    scanHistory: "స్కాన్ చరిత్ర",
    howItWorks: "ఎలా పనిచేస్తుంది",
    step1: "స్మార్ట్ డస్ట్‌బిన్ కనుగొనండి",
    step1Desc: "మీ దగ్గర EcoRewards స్మార్ట్ డస్ట్‌బిన్‌ను కనుగొనండి",
    step2: "QR కోడ్ స్కాన్ చేయండి",
    step2Desc: "డస్ట్‌బిన్‌పై ఉన్న QR కోడ్‌ను స్కాన్ చేయండి",
    step3: "కోడ్ ఎంటర్ చేయండి",
    step3Desc: "యాప్‌లో డస్ట్‌బిన్ కోడ్ ఎంటర్ చేయండి",
    step4: "బహుమతులు సంపాదించండి",
    step4Desc: "తక్షణ బహుమతులు మరియు పాయింట్లు పొందండి",
    usageLimit: "వాడుక పరిమితి",
    usageLimitDesc: "కఠిన పరిమితి: ప్రతి వినియోగదారుకు రోజుకు గరిష్టంగా 2 సార్లు డస్ట్‌బిన్ వాడుక",
    citiesLeading: "నగరాలు మార్పు తెస్తున్నాయి",
    citiesLeadingSub: "ఏ నగరాలు స్థిరత్వంలో ముందున్నాయో చూడండి",
    viewLeaderboard: "పూర్తి లీడర్‌బోర్డ్ చూడండి",
    seeMoreCities: "మరిన్ని నగరాలు చూడండి",
    participation: "పాల్గొనడం",
    wasteDiverted: "చెత్త మళ్లించబడింది",
    whatHappens: "మీ చెత్తకు ఏమవుతుంది?",
    collection: "సేకరణ",
    collectionDesc: "మీ చెత్త మా స్మార్ట్ డస్ట్‌బిన్‌ల నుండి సేకరించి వెంటనే క్రమబద్ధీకరించబడుతుంది।",
    sorting: "క్రమబద్ధీకరణ",
    sortingDesc: "అధునాతన సాంకేతికత రీసైకిల్ చేయగలవాటిని మరియు చేయలేని వాటిని వేరు చేస్తుంది।",
    recycling: "రీసైక్లింగ్",
    recyclingDesc: "రీసైకిల్ చేయగల పదార్థాలను కొత్త ఉత్పత్తులుగా మారుస్తారు।",
    energyRecovery: "శక్తి పునరుద్ధరణ",
    energyRecoveryDesc: "రీసైకిల్ చేయలేని చెత్తను పర్యావరణ అనుకూల పద్ధతిలో శక్తిగా మారుస్తారు।",
    statsNote: "గమనిక: చూపించిన గణాంకాలు ప్రదర్శన కోసం ఉదాహరణ విలువలు",
    wasteFromLandfills: "ల్యాండ్‌ఫిల్‌ల నుండి మళ్లించిన చెత్త",
    tonsRecycled: "ఈ నెలలో రీసైకిల్ చేసిన టన్నులు",
    emissionsReduction: "హానికర ఉద్గారాల తగ్గింపు",
    
    // Leaderboard
    cityLeaderboard: "నగర స్థిరత్వ లీడర్‌బోర్డ్",
    cityLeaderboardSub: "అత్యధిక పర్యావరణ ప్రభావాన్ని చూపుతున్న నగరాల పౌరులను జరుపుకుందాం",
    wasteRecycledMonth: "ఈ నెలలో రీసైకిల్ చేసిన చెత్త",
    activeUsers: "క్రియాశీల వినియోగదారులు",
    smartDustbins: "స్మార్ట్ డస్ట్‌బిన్‌లు",
    back: "వెనుకకు",
    whyMatters: "ఇది ఎందుకు ముఖ్యం",
    citiesThrive: "నగరాలు అభివృద్ధి చెందుతాయి",
    citiesThriveDesc: "అధిక EcoRewards పాల్గొనడం ఉన్న నగరాలలో స్వచ్ఛమైన వీధులు, తక్కువ కాలుష్యం మరియు మెరుగైన జీవన నాణ్యత కనిపిస్తుంది।",
    realImpact: "నిజమైన ప్రభావం",
    realImpactDesc: "రీసైకిల్ చేసిన ప్రతి కిలో చెత్త హానికర మీథేన్ ఉద్గారాలను నిరోధిస్తుంది మరియు ల్యాండ్‌ఫిల్ కాలుష్యాన్ని తగ్గిస్తుంది।",
    winWin: "రెండింటికీ లాభం",
    winWinDesc: "పౌరులు స్మార్ట్ డస్ట్‌బిన్‌లను ఉపయోగించి బహుమతులు పొందుతారు మరియు తమ నగరాన్ని స్వచ్ఛంగా మారుస్తారు।",
    
    // Report
    reportIssue: "సమస్యను నివేదించండి",
    whatToReport: "మీరు ఏమి నివేదించాలనుకుంటున్నారు?",
    selectIssue: "సమస్య రకాన్ని ఎంచుకోండి",
    brokenDustbin: "విరిగిన డస్ట్‌బిన్",
    fullDustbin: "నిండిన డస్ట్‌బిన్",
    technicalIssue: "సాంకేతిక సమస్య",
    qrProblem: "QR కోడ్ సమస్య",
    locationIssue: "స్థానం సమస్య",
    other: "ఇతరం",
    elaborate: "దయచేసి సమస్యను వివరంగా చెప్పండి:",
    describeProblem: "సమస్యను వివరంగా వివరించండి... (ఉదా., స్థానం, డస్ట్‌బిన్ కోడ్, ఏమి జరిగింది)",
    cancel: "రద్దు చేయి",
    submitReport: "నివేదిక సమర్పించండి",
    
    // Messages
    thankYouReport: "మీ నివేదిక కోసం ధన్యవాదాలు!\n\nమేము మీ అభిప్రాయాన్ని అందుకున్నాము మరియు త్వరలో దానిని పరిష్కరిస్తాము।",
    selectIssueError: "దయచేసి సమస్య రకాన్ని ఎంచుకోండి మరియు వివరాలు ఇవ్వండి।",
    dailyLimitReached: "రోజువారీ పరిమితి చేరుకుంది! మీరు రోజుకు కేవలం 5 సార్లు మాత్రమే డస్ట్‌బిన్‌లను ఉపయోగించవచ్చు। రేపు తిరిగి రండి!",
    enterDustbinCode: "దయచేసి డస్ట్‌బిన్ కోడ్ ఎంటర్ చేయండి",
    checkingLocation: "మీ స్థానాన్ని తనిఖీ చేస్తోంది...",
    locationVerified: "స్థానం ధృవీకరించబడింది। కోడ్ తనిఖీ చేస్తోంది...",
    tooFar: "మీరు డస్ట్‌బిన్ నుండి చాలా దూరంగా ఉన్నారు",
    getCloser: "దయచేసి దగ్గరకు రండి।",
    success: "విజయం!",
    earnedPoints: "మీరు సంపాదించారు"
  },
  ta: {
    // Onboarding
    welcome: "EcoRewards க்கு வரவேற்கிறோம்",
    tagline: "புத்திசாலித்தனமாக மறுசுழற்சி செய்யுங்கள், வெகுமதிகளைப் பெறுங்கள்",
    selectLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    continue: "தொடரவும்",
    getStarted: "தொடங்குங்கள்",
    learnHow: "எப்படி செயல்படுகிறது என்பதை அறியவும்",
    skip: "தவிர்க்கவும்",
    congratulations: "வாழ்த்துக்கள்!",
    welcomeReward: "நீங்கள் வெகுமதியைப் பெற்றுள்ளீர்கள்!",
    tutorialStep1Title: "QR குறியீட்டை ஸ்கேன் செய்யவும்",
    tutorialStep1Desc: "ஸ்மார்ட் டஸ்ட்பினைக் கண்டுபிடித்து அதில் உள்ள QR குறியீட்டை ஸ்கேன் செய்யவும்",
    tutorialStep2Title: "டஸ்ட்பின் குறியீட்டை உள்ளிடவும்",
    tutorialStep2Desc: "QR இலிருந்து கிடைத்த டஸ்ட்பின் குறியீட்டை ஆப்பில் டைப் செய்யவும்",
    tutorialStep3Title: "கழிவுகளை அகற்றவும்",
    tutorialStep3Desc: "உங்கள் மறுசுழற்சி செய்யக்கூடிய கழிவுகளை டஸ்ட்பினில் சரியாக அகற்றவும்",
    tutorialStep4Title: "வெகுமதிகளைப் பெறுங்கள்",
    tutorialStep4Desc: "கூட்டாண்மை கடைகளில் உடனடி வெகுமதிகள் மற்றும் தள்ளுபடிகளைப் பெறுங்கள்",
    tutorialStep5Title: "மாற்றத்தை உருவாக்குங்கள்",
    tutorialStep5Desc: "உங்கள் சுற்றுச்சூழல் பங்களிப்பைக் கண்காணித்து உங்கள் தாக்கத்தைப் பார்க்கவும்",
    next: "அடுத்து",
    finish: "முடிவு",
    signIn: "Google மூலம் உள்நுழையவும்",
    earnRewards: "மறுசுழற்சிக்கு வெகுமதிகளைப் பெறுங்கள்",
    getDiscounts: "கூட்டாண்மை கடைகளில் தள்ளுபடிகளைப் பெறுங்கள்",
    helpPlanet: "தூய்மையான கிரகத்தை உருவாக்க உதவுங்கள்",
    
    // Dashboard
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    scanQRPrompt: "வெகுமதிகளைப் பெற டஸ்ட்பின் QR குறியீட்டை ஸ்கேன் செய்து கீழே குறியீட்டை உள்ளிடவும்",
    enterCode: "டஸ்ட்பின் குறியீட்டை உள்ளிடவும்",
    enterCodePlaceholder: "குறியீட்டை உள்ளிடவும் (எ.கா., DBN001)",
    submit: "சமர்ப்பித்து வெகுமதிகளைப் பெறுங்கள்",
    myRewards: "எனது வெகுமதிகள்",
    points: "புள்ளிகள்",
    scanHistory: "ஸ்கேன் வரலாறு",
    howItWorks: "எப்படி செயல்படுகிறது",
    step1: "ஸ்மார்ட் டஸ்ட்பினைக் கண்டறியவும்",
    step1Desc: "உங்களுக்கு அருகில் உள்ள EcoRewards ஸ்மார்ட் டஸ்ட்பினைக் கண்டுபிடிக்கவும்",
    step2: "QR குறியீட்டை ஸ்கேன் செய்யவும்",
    step2Desc: "டஸ்ட்பினில் உள்ள QR குறியீட்டை ஸ்கேன் செய்யவும்",
    step3: "குறியீட்டை உள்ளிடவும்",
    step3Desc: "ஆப்ஸில் டஸ்ட்பின் குறியீட்டை உள்ளிடவும்",
    step4: "வெகுமதிகளைப் பெறுங்கள்",
    step4Desc: "உடனடி வெகுமதிகள் மற்றும் புள்ளிகளைப் பெறுங்கள்",
    usageLimit: "பயன்பாட்டு வரம்பு",
    usageLimitDesc: "கடுமையான வரம்பு: ஒரு பயனருக்கு ஒரு நாளைக்கு அதிகபட்சம் 2 முறை டஸ்ட்பின் பயன்பாடு",
    citiesLeading: "மாற்றத்தை உருவாக்கும் நகரங்கள்",
    citiesLeadingSub: "நிலைத்தன்மையில் முன்னணியில் இருக்கும் நகரங்களைப் பாருங்கள்",
    viewLeaderboard: "முழு லீடர்போர்டைப் பார்க்கவும்",
    seeMoreCities: "மேலும் நகரங்களைப் பார்க்கவும்",
    participation: "பங்கேற்பு",
    wasteDiverted: "திசை திருப்பப்பட்ட கழிவு",
    whatHappens: "உங்கள் குப்பைக்கு என்ன நடக்கிறது?",
    collection: "சேகரிப்பு",
    collectionDesc: "உங்கள் கழிவு எங்கள் ஸ்மார்ட் டஸ்ட்பின்களில் இருந்து சேகரிக்கப்பட்டு உடனடியாக வரிசைப்படுத்தப்படுகிறது.",
    sorting: "வரிசைப்படுத்துதல்",
    sortingDesc: "மேம்பட்ட தொழில்நுட்பம் மறுசுழற்சி செய்யக்கூடியவை மற்றும் செய்ய முடியாதவற்றைப் பிரிக்கிறது.",
    recycling: "மறுசுழற்சி",
    recyclingDesc: "மறுசுழற்சி செய்யக்கூடிய பொருட்கள் புதிய தயாரிப்புகளாக மாற்றப்படுகின்றன.",
    energyRecovery: "ஆற்றல் மீட்பு",
    energyRecoveryDesc: "மறுசுழற்சி செய்ய முடியாத கழிவு சுற்றுச்சூழல் நட்பு முறையில் ஆற்றலாக மாற்றப்படுகிறது.",
    statsNote: "குறிப்பு: காட்டப்பட்ட புள்ளிவிவரங்கள் ஆர்ப்பாட்ட நோக்கங்களுக்கான உதாரண மதிப்புகள்",
    wasteFromLandfills: "நிலப்பரப்பில் இருந்து திசை திருப்பப்பட்ட கழிவு",
    tonsRecycled: "இந்த மாதம் மறுசுழற்சி செய்யப்பட்ட டன்கள்",
    emissionsReduction: "தீங்கு விளைவிக்கும் உமிழ்வுகளில் குறைப்பு",
    
    // Leaderboard
    cityLeaderboard: "நகர நிலைத்தன்மை லீடர்போர்டு",
    cityLeaderboardSub: "மிகப்பெரிய சுற்றுச்சூழல் தாக்கத்தை ஏற்படுத்தும் நகரங்களின் குடிமக்களைக் கொண்டாடுங்கள்",
    wasteRecycledMonth: "இந்த மாதம் மறுசுழற்சி செய்யப்பட்ட கழிவு",
    activeUsers: "செயலில் உள்ள பயனர்கள்",
    smartDustbins: "ஸ்மார்ட் டஸ்ட்பின்கள்",
    back: "பின்னால்",
    whyMatters: "இது ஏன் முக்கியம்",
    citiesThrive: "நகரங்கள் செழிக்கின்றன",
    citiesThriveDesc: "அதிக EcoRewards பங்கேற்பு உள்ள நகரங்களில் சுத்தமான தெருக்கள், குறைந்த மாசுபாடு மற்றும் மேம்பட்ட வாழ்க்கைத் தரம் காணப்படுகிறது.",
    realImpact: "உண்மையான தாக்கம்",
    realImpactDesc: "மறுசுழற்சி செய்யப்படும் ஒவ்வொரு கிலோ கழிவும் தீங்கு விளைவிக்கும் மீத்தேன் உமிழ்வைத் தடுக்கிறது மற்றும் நிலப்பரப்பு மாசுபாட்டைக் குறைக்கிறது.",
    winWin: "இரு தரப்பினருக்கும் லாபம்",
    winWinDesc: "குடிமக்கள் ஸ்மார்ட் டஸ்ட்பின்களைப் பயன்படுத்தி வெகுமதிகளைப் பெறுகிறார்கள் மற்றும் தங்கள் நகரத்தை சுத்தமாக மாற்ற உதவுகிறார்கள்.",
    
    // Report
    reportIssue: "சிக்கலைப் புகாரளிக்கவும்",
    whatToReport: "நீங்கள் என்ன புகாரளிக்க விரும்புகிறீர்கள்?",
    selectIssue: "சிக்கல் வகையைத் தேர்ந்தெடுக்கவும்",
    brokenDustbin: "உடைந்த டஸ்ட்பின்",
    fullDustbin: "நிறைந்த டஸ்ட்பின்",
    technicalIssue: "தொழில்நுட்ப சிக்கல்",
    qrProblem: "QR குறியீட்டு சிக்கல்",
    locationIssue: "இட சிக்கல்",
    other: "மற்றவை",
    elaborate: "தயவுசெய்து சிக்கலை விரிவாக விளக்கவும்:",
    describeProblem: "சிக்கலை விரிவாக விவரிக்கவும்... (எ.கா., இடம், டஸ்ட்பின் குறியீடு, என்ன நடந்தது)",
    cancel: "ரத்து செய்",
    submitReport: "புகார் சமர்ப்பிக்கவும்",
    
    // Messages
    thankYouReport: "உங்கள் புகாருக்கு நன்றி!\n\nஎங்களுக்கு உங்கள் கருத்து கிடைத்துள்ளது, விரைவில் அதைத் தீர்ப்போம்.",
    selectIssueError: "தயவுசெய்து சிக்கல் வகையைத் தேர்ந்தெடுத்து விவரங்களை வழங்கவும்.",
    dailyLimitReached: "தினசரி வரம்பு அடைந்தது! நீங்கள் ஒரு நாளைக்கு 5 முறை மட்டுமே டஸ்ட்பின்களைப் பயன்படுத்த முடியும். நாளை மீண்டும் வாருங்கள்!",
    enterDustbinCode: "தயவுசெய்து டஸ்ட்பின் குறியீட்டை உள்ளிடவும்",
    checkingLocation: "உங்கள் இடத்தைச் சரிபார்க்கிறது...",
    locationVerified: "இடம் சரிபார்க்கப்பட்டது। குறியீடு சரிபார்க்கப்படுகிறது...",
    tooFar: "நீங்கள் டஸ்ட்பினிலிருந்து மிகவும் தொலைவில் இருக்கிறீர்கள்",
    getCloser: "தயவுசெய்து நெருக்கமாக வாருங்கள்.",
    success: "வெற்றி!",
    earnedPoints: "நீங்கள் சம்பாதித்துள்ளீர்கள்"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || null;
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => {
    return translations[language || 'en'][key] || key;
  };

  const value = {
    language,
    changeLanguage,
    t,
    translations
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

